/* AUTO-GENERATED by tools/build_catalog.py — do not edit by hand. */
window.IMPRINT_CATALOG = {
 "categories": [
  {
   "id": "bags",
   "name": "Bags & Totes",
   "desc": "Luxury shopping, gift & garment bags with foil, emboss and ribbon handles."
  },
  {
   "id": "boxes",
   "name": "Rigid & Gift Boxes",
   "desc": "Magnetic, rigid lid, book and folding boxes for premium unboxing."
  },
  {
   "id": "mailer",
   "name": "Mailer & Shipping",
   "desc": "Self-locking e-commerce mailers and branded shipping cartons."
  },
  {
   "id": "food",
   "name": "Food & Gourmet",
   "desc": "Bakery, chocolate, coffee and confectionery packaging."
  },
  {
   "id": "beauty",
   "name": "Beauty & Fragrance",
   "desc": "Perfume, cosmetic and candle packaging with a jewel-like finish."
  },
  {
   "id": "jewellery",
   "name": "Jewellery & Keepsake",
   "desc": "Ring, velvet and keepsake boxes that protect and impress."
  },
  {
   "id": "tubes",
   "name": "Tubes & Cylinders",
   "desc": "Round rigid tubes for spirits, cosmetics, posters and gifting."
  },
  {
   "id": "floral",
   "name": "Floral & Bouquet",
   "desc": "Bouquet wraps and flower boxes for florists and events."
  },
  {
   "id": "stationery",
   "name": "Stationery & Cards",
   "desc": "Branded stationery sets, cards and enclosures."
  }
 ],
 "tags": {
  "hot": {
   "label": "Hot",
   "tone": "hot"
  },
  "trending": {
   "label": "Trending",
   "tone": "trend"
  },
  "new": {
   "label": "New",
   "tone": "new"
  },
  "bestseller": {
   "label": "Bestseller",
   "tone": "best"
  },
  "editors": {
   "label": "Editor's pick",
   "tone": "editor"
  },
  "eco": {
   "label": "Eco",
   "tone": "eco"
  },
  "foil": {
   "label": "Foil",
   "tone": "foil"
  },
  "limited": {
   "label": "Limited",
   "tone": "limited"
  }
 },
 "products": [
  {
   "id": "honeyloom-gift-bag",
   "name": "Honeyloom Gift Bag",
   "category": "bags",
   "image": {
    "l": "templates/renders/honey-gift-bag-1-l.webp",
    "s": "templates/renders/honey-gift-bag-1-s.webp",
    "lw": 1200,
    "sw": 480,
    "h": 723
   },
   "gallery": [
    {
     "l": "templates/renders/honey-gift-bag-1-l.webp",
     "s": "templates/renders/honey-gift-bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "templates/renders/honey-gift-bag-2-l.webp",
     "s": "templates/renders/honey-gift-bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "templates/renders/honey-gift-bag-3-l.webp",
     "s": "templates/renders/honey-gift-bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "crescent-press",
    "najm-packaging"
   ],
   "price": 12.5,
   "tags": [
    "foil",
    "hot",
    "editors"
   ],
   "rating": 5.0,
   "reviews": 63,
   "blurb": "A foil honeycomb bottle bag with editable wordmark — the flagship Imprint template. Fully customisable in 3D.",
   "featured": true,
   "template": "honey-gift-bag",
   "href": "honeyloom-gift-bag/",
   "rich": true
  },
  {
   "id": "coffee-cup",
   "name": "Artisan Coffee Cup",
   "category": "food",
   "image": {
    "l": "assets/products/coffee-cup-1-l.webp",
    "s": "assets/products/coffee-cup-1-s.webp",
    "lw": 1024,
    "sw": 480,
    "h": 617
   },
   "gallery": [
    {
     "l": "assets/products/coffee-cup-1-l.webp",
     "s": "assets/products/coffee-cup-1-s.webp",
     "lw": 1024,
     "sw": 480,
     "h": 617
    },
    {
     "l": "assets/products/coffee-cup-2-l.webp",
     "s": "assets/products/coffee-cup-2-s.webp",
     "lw": 1024,
     "sw": 480,
     "h": 617
    },
    {
     "l": "assets/products/coffee-cup-3-l.webp",
     "s": "assets/products/coffee-cup-3-s.webp",
     "lw": 1024,
     "sw": 480,
     "h": 617
    },
    {
     "l": "assets/products/coffee-cup-4-l.webp",
     "s": "assets/products/coffee-cup-4-s.webp",
     "lw": 1024,
     "sw": 480,
     "h": 617
    },
    {
     "l": "assets/products/coffee-cup-5-l.webp",
     "s": "assets/products/coffee-cup-5-s.webp",
     "lw": 1024,
     "sw": 480,
     "h": 617
    }
   ],
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 1.8,
   "tags": [
    "new",
    "hot",
    "eco"
   ],
   "rating": 4.9,
   "reviews": 21,
   "blurb": "A double-wall paper coffee cup you can brand across the body, sleeve and base in real-time 3D — the lid stays clean. A ready Imprint template with its own cup studio.",
   "featured": true,
   "template": "coffee-cup",
   "configurator": "configurator-cup.html",
   "href": "coffee-cup/",
   "size": "M"
  },
  {
   "id": "gold-mandala-paper-gift-bag",
   "name": "Gold Mandala Paper Gift Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/gold-mandala-paper-gift-bag-l.webp",
    "s": "assets/products/gold-mandala-paper-gift-bag-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 8.0,
   "tags": [
    "foil",
    "trending"
   ],
   "rating": 4.3,
   "reviews": 178,
   "gallery": [
    {
     "l": "assets/products/gold-mandala-paper-gift-bag-l.webp",
     "s": "assets/products/gold-mandala-paper-gift-bag-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Gold Mandala Paper Gift Bag — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "gold-mandala-paper-gift-bag/"
  },
  {
   "id": "navy-gold-floral-rigid-box",
   "name": "Navy Gold Floral Rigid Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/navy-gold-floral-rigid-box-l.webp",
    "s": "assets/products/navy-gold-floral-rigid-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 23.4,
   "tags": [
    "foil"
   ],
   "rating": 4.8,
   "reviews": 39,
   "gallery": [
    {
     "l": "assets/products/navy-gold-floral-rigid-box-l.webp",
     "s": "assets/products/navy-gold-floral-rigid-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Navy Gold Floral Rigid Box — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-gold-floral-rigid-box/"
  },
  {
   "id": "ivory-gold-ornate-book-box",
   "name": "Ivory Gold Ornate Book Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/ivory-gold-ornate-book-box-l.webp",
    "s": "assets/products/ivory-gold-ornate-book-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 34.6,
   "tags": [
    "foil",
    "bestseller"
   ],
   "rating": 4.9,
   "reviews": 27,
   "gallery": [
    {
     "l": "assets/products/ivory-gold-ornate-book-box-l.webp",
     "s": "assets/products/ivory-gold-ornate-book-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Ivory Gold Ornate Book Box — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-gold-ornate-book-box/"
  },
  {
   "id": "burgundy-chocolate-gift-box",
   "name": "Burgundy Chocolate Gift Box",
   "category": "food",
   "image": {
    "l": "assets/products/burgundy-chocolate-gift-box-l.webp",
    "s": "assets/products/burgundy-chocolate-gift-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "kwame-mensah",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 14.8,
   "tags": [],
   "rating": 4.9,
   "reviews": 54,
   "gallery": [
    {
     "l": "assets/products/burgundy-chocolate-gift-box-l.webp",
     "s": "assets/products/burgundy-chocolate-gift-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Burgundy Chocolate Gift Box — a designer template by Kwame Mensah. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "burgundy-chocolate-gift-box/"
  },
  {
   "id": "kraft-mailer-box-gold-emblem",
   "name": "Kraft Mailer Box Gold Emblem",
   "category": "mailer",
   "image": {
    "l": "assets/products/kraft-mailer-box-gold-emblem-l.webp",
    "s": "assets/products/kraft-mailer-box-gold-emblem-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "aminata-diallo",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 7.5,
   "tags": [
    "foil",
    "eco",
    "new"
   ],
   "rating": 4.3,
   "reviews": 161,
   "gallery": [
    {
     "l": "assets/products/kraft-mailer-box-gold-emblem-l.webp",
     "s": "assets/products/kraft-mailer-box-gold-emblem-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Kraft Mailer Box Gold Emblem — a designer template by Aminata Diallo. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "kraft-mailer-box-gold-emblem/"
  },
  {
   "id": "white-cake-box",
   "name": "White Cake Box",
   "category": "food",
   "image": {
    "l": "assets/products/white-cake-box-l.webp",
    "s": "assets/products/white-cake-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "kenji-sato",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 13.2,
   "tags": [],
   "rating": 4.8,
   "reviews": 18,
   "gallery": [
    {
     "l": "assets/products/white-cake-box-l.webp",
     "s": "assets/products/white-cake-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "White Cake Box — a designer template by Kenji Sato. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "white-cake-box/"
  },
  {
   "id": "kraft-cylinder-tube",
   "name": "Kraft Cylinder Tube",
   "category": "tubes",
   "image": {
    "l": "assets/products/kraft-cylinder-tube-l.webp",
    "s": "assets/products/kraft-cylinder-tube-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 10.3,
   "tags": [
    "eco",
    "hot",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 145,
   "gallery": [
    {
     "l": "assets/products/kraft-cylinder-tube-l.webp",
     "s": "assets/products/kraft-cylinder-tube-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Kraft Cylinder Tube — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "kraft-cylinder-tube/"
  },
  {
   "id": "blush-pink-round-gift-box",
   "name": "Blush Pink Round Gift Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/blush-pink-round-gift-box-l.webp",
    "s": "assets/products/blush-pink-round-gift-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 27.0,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 189,
   "gallery": [
    {
     "l": "assets/products/blush-pink-round-gift-box-l.webp",
     "s": "assets/products/blush-pink-round-gift-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Blush Pink Round Gift Box — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "blush-pink-round-gift-box/"
  },
  {
   "id": "ivory-jewelry-box-velvet",
   "name": "Ivory Jewelry Box Velvet",
   "category": "jewellery",
   "image": {
    "l": "assets/products/ivory-jewelry-box-velvet-l.webp",
    "s": "assets/products/ivory-jewelry-box-velvet-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 43.5,
   "tags": [
    "new"
   ],
   "rating": 4.3,
   "reviews": 71,
   "gallery": [
    {
     "l": "assets/products/ivory-jewelry-box-velvet-l.webp",
     "s": "assets/products/ivory-jewelry-box-velvet-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Ivory Jewelry Box Velvet — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-jewelry-box-velvet/"
  },
  {
   "id": "black-garment-bag",
   "name": "Black Garment Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/black-garment-bag-l.webp",
    "s": "assets/products/black-garment-bag-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "mateo-herrera",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 12.8,
   "tags": [
    "bestseller"
   ],
   "rating": 4.8,
   "reviews": 51,
   "gallery": [
    {
     "l": "assets/products/black-garment-bag-l.webp",
     "s": "assets/products/black-garment-bag-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Black Garment Bag — a designer template by Mateo Herrera. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-garment-bag/"
  },
  {
   "id": "black-perfume-box",
   "name": "Black Perfume Box",
   "category": "beauty",
   "image": {
    "l": "assets/products/black-perfume-box-l.webp",
    "s": "assets/products/black-perfume-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 43.5,
   "tags": [
    "trending"
   ],
   "rating": 4.9,
   "reviews": 191,
   "gallery": [
    {
     "l": "assets/products/black-perfume-box-l.webp",
     "s": "assets/products/black-perfume-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Black Perfume Box — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-perfume-box/"
  },
  {
   "id": "dark-chocolate-truffle-box",
   "name": "Dark Chocolate Truffle Box",
   "category": "food",
   "image": {
    "l": "assets/products/dark-chocolate-truffle-box-l.webp",
    "s": "assets/products/dark-chocolate-truffle-box-s.webp",
    "lw": 240,
    "sw": 240,
    "h": 320
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 11.8,
   "tags": [
    "hot"
   ],
   "rating": 4.5,
   "reviews": 78,
   "gallery": [
    {
     "l": "assets/products/dark-chocolate-truffle-box-l.webp",
     "s": "assets/products/dark-chocolate-truffle-box-s.webp",
     "lw": 240,
     "sw": 240,
     "h": 320
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Dark Chocolate Truffle Box — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "dark-chocolate-truffle-box/"
  },
  {
   "id": "green-geometric-paper-gift-bag",
   "name": "Green Geometric Paper Gift Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/green-geometric-paper-gift-bag-l.webp",
    "s": "assets/products/green-geometric-paper-gift-bag-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "kwame-mensah",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 10.9,
   "tags": [
    "new"
   ],
   "rating": 4.6,
   "reviews": 65,
   "gallery": [
    {
     "l": "assets/products/green-geometric-paper-gift-bag-l.webp",
     "s": "assets/products/green-geometric-paper-gift-bag-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-1-l.webp",
     "s": "assets/bags/bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Green Geometric Paper Gift Bag — a designer template by Kwame Mensah. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "green-geometric-paper-gift-bag/"
  },
  {
   "id": "cream-ribbon-magnetic-gift-box",
   "name": "Cream Ribbon Magnetic Gift Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/cream-ribbon-magnetic-gift-box-l.webp",
    "s": "assets/products/cream-ribbon-magnetic-gift-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 36.4,
   "tags": [
    "hot"
   ],
   "rating": 4.3,
   "reviews": 29,
   "gallery": [
    {
     "l": "assets/products/cream-ribbon-magnetic-gift-box-l.webp",
     "s": "assets/products/cream-ribbon-magnetic-gift-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-6-l.webp",
     "s": "assets/bags/bag-6-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Cream Ribbon Magnetic Gift Box — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cream-ribbon-magnetic-gift-box/"
  },
  {
   "id": "black-patterned-mailer-box",
   "name": "Black Patterned Mailer Box",
   "category": "mailer",
   "image": {
    "l": "assets/products/black-patterned-mailer-box-l.webp",
    "s": "assets/products/black-patterned-mailer-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "aminata-diallo",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 14.1,
   "tags": [
    "new"
   ],
   "rating": 4.9,
   "reviews": 44,
   "gallery": [
    {
     "l": "assets/products/black-patterned-mailer-box-l.webp",
     "s": "assets/products/black-patterned-mailer-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Black Patterned Mailer Box — a designer template by Aminata Diallo. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-patterned-mailer-box/"
  },
  {
   "id": "navy-velvet-ring-box",
   "name": "Navy Velvet Ring Box",
   "category": "jewellery",
   "image": {
    "l": "assets/products/navy-velvet-ring-box-l.webp",
    "s": "assets/products/navy-velvet-ring-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 22.0,
   "tags": [],
   "rating": 4.9,
   "reviews": 162,
   "gallery": [
    {
     "l": "assets/products/navy-velvet-ring-box-l.webp",
     "s": "assets/products/navy-velvet-ring-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Navy Velvet Ring Box — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-velvet-ring-box/"
  },
  {
   "id": "white-window-gift-box-ribbon",
   "name": "White Window Gift Box Ribbon",
   "category": "boxes",
   "image": {
    "l": "assets/products/white-window-gift-box-ribbon-l.webp",
    "s": "assets/products/white-window-gift-box-ribbon-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "kenji-sato",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 38.8,
   "tags": [],
   "rating": 4.8,
   "reviews": 165,
   "gallery": [
    {
     "l": "assets/products/white-window-gift-box-ribbon-l.webp",
     "s": "assets/products/white-window-gift-box-ribbon-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "White Window Gift Box Ribbon — a designer template by Kenji Sato. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "white-window-gift-box-ribbon/"
  },
  {
   "id": "terracotta-cylinder-tube",
   "name": "Terracotta Cylinder Tube",
   "category": "tubes",
   "image": {
    "l": "assets/products/terracotta-cylinder-tube-l.webp",
    "s": "assets/products/terracotta-cylinder-tube-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "mateo-herrera",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 19.7,
   "tags": [],
   "rating": 4.9,
   "reviews": 179,
   "gallery": [
    {
     "l": "assets/products/terracotta-cylinder-tube-l.webp",
     "s": "assets/products/terracotta-cylinder-tube-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": true,
   "blurb": "Terracotta Cylinder Tube — a designer template by Mateo Herrera. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "terracotta-cylinder-tube/"
  },
  {
   "id": "burgundy-rigid-lid-box",
   "name": "Burgundy Rigid Lid Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/burgundy-rigid-lid-box-l.webp",
    "s": "assets/products/burgundy-rigid-lid-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "kwame-mensah",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 39.8,
   "tags": [
    "trending"
   ],
   "rating": 4.6,
   "reviews": 109,
   "gallery": [
    {
     "l": "assets/products/burgundy-rigid-lid-box-l.webp",
     "s": "assets/products/burgundy-rigid-lid-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Burgundy Rigid Lid Box — a designer template by Kwame Mensah. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "burgundy-rigid-lid-box/"
  },
  {
   "id": "blush-pink-bouquet-wrap",
   "name": "Blush Pink Bouquet Wrap",
   "category": "floral",
   "image": {
    "l": "assets/products/blush-pink-bouquet-wrap-l.webp",
    "s": "assets/products/blush-pink-bouquet-wrap-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 20.9,
   "tags": [
    "new"
   ],
   "rating": 4.5,
   "reviews": 187,
   "gallery": [
    {
     "l": "assets/products/blush-pink-bouquet-wrap-l.webp",
     "s": "assets/products/blush-pink-bouquet-wrap-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Blush Pink Bouquet Wrap — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "blush-pink-bouquet-wrap/"
  },
  {
   "id": "gray-garment-bag",
   "name": "Gray Garment Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/gray-garment-bag-l.webp",
    "s": "assets/products/gray-garment-bag-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 12.4,
   "tags": [
    "hot"
   ],
   "rating": 4.7,
   "reviews": 43,
   "gallery": [
    {
     "l": "assets/products/gray-garment-bag-l.webp",
     "s": "assets/products/gray-garment-bag-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Gray Garment Bag — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "gray-garment-bag/"
  },
  {
   "id": "black-perfume-drawer-box",
   "name": "Black Perfume Drawer Box",
   "category": "beauty",
   "image": {
    "l": "assets/products/black-perfume-drawer-box-l.webp",
    "s": "assets/products/black-perfume-drawer-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 25.4,
   "tags": [
    "bestseller"
   ],
   "rating": 4.9,
   "reviews": 130,
   "gallery": [
    {
     "l": "assets/products/black-perfume-drawer-box-l.webp",
     "s": "assets/products/black-perfume-drawer-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Black Perfume Drawer Box — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-perfume-drawer-box/"
  },
  {
   "id": "navy-tall-bottle-box",
   "name": "Navy Tall Bottle Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/navy-tall-bottle-box-l.webp",
    "s": "assets/products/navy-tall-bottle-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 41.0,
   "tags": [
    "editors"
   ],
   "rating": 4.6,
   "reviews": 151,
   "gallery": [
    {
     "l": "assets/products/navy-tall-bottle-box-l.webp",
     "s": "assets/products/navy-tall-bottle-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Navy Tall Bottle Box — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-tall-bottle-box/"
  },
  {
   "id": "ivory-cube-favor-boxes",
   "name": "Ivory Cube Favor Boxes",
   "category": "boxes",
   "image": {
    "l": "assets/products/ivory-cube-favor-boxes-l.webp",
    "s": "assets/products/ivory-cube-favor-boxes-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "kenji-sato",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 15.3,
   "tags": [
    "hot"
   ],
   "rating": 4.9,
   "reviews": 125,
   "gallery": [
    {
     "l": "assets/products/ivory-cube-favor-boxes-l.webp",
     "s": "assets/products/ivory-cube-favor-boxes-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Ivory Cube Favor Boxes — a designer template by Kenji Sato. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-cube-favor-boxes/"
  },
  {
   "id": "ab-monogram-navy-chocolate-box",
   "name": "AB Monogram Navy Chocolate Box",
   "category": "food",
   "image": {
    "l": "assets/products/ab-monogram-navy-chocolate-box-l.webp",
    "s": "assets/products/ab-monogram-navy-chocolate-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "amina-yusuf",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 19.4,
   "tags": [
    "bestseller"
   ],
   "rating": 4.8,
   "reviews": 190,
   "gallery": [
    {
     "l": "assets/products/ab-monogram-navy-chocolate-box-l.webp",
     "s": "assets/products/ab-monogram-navy-chocolate-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-9-l.webp",
     "s": "assets/bags/bag-9-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "AB Monogram Navy Chocolate Box — a designer template by Amina Yusuf. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ab-monogram-navy-chocolate-box/"
  },
  {
   "id": "la-petite-boutique-pink-bags",
   "name": "La Petite Boutique Pink Bags",
   "category": "bags",
   "image": {
    "l": "assets/products/la-petite-boutique-pink-bags-l.webp",
    "s": "assets/products/la-petite-boutique-pink-bags-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "amina-yusuf",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 13.5,
   "tags": [
    "new",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 39,
   "gallery": [
    {
     "l": "assets/products/la-petite-boutique-pink-bags-l.webp",
     "s": "assets/products/la-petite-boutique-pink-bags-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-6-l.webp",
     "s": "assets/bags/bag-6-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "La Petite Boutique Pink Bags — a designer template by Amina Yusuf. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "la-petite-boutique-pink-bags/"
  },
  {
   "id": "artisan-coffee-green-tin",
   "name": "Artisan Coffee Green Tin",
   "category": "food",
   "image": {
    "l": "assets/products/artisan-coffee-green-tin-l.webp",
    "s": "assets/products/artisan-coffee-green-tin-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 10.8,
   "tags": [
    "new"
   ],
   "rating": 4.9,
   "reviews": 40,
   "gallery": [
    {
     "l": "assets/products/artisan-coffee-green-tin-l.webp",
     "s": "assets/products/artisan-coffee-green-tin-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Artisan Coffee Green Tin — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "artisan-coffee-green-tin/"
  },
  {
   "id": "sugar-and-spice-bakery-box",
   "name": "Sugar & Spice Bakery Box",
   "category": "food",
   "image": {
    "l": "assets/products/sugar-and-spice-bakery-box-l.webp",
    "s": "assets/products/sugar-and-spice-bakery-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "aminata-diallo",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 13.3,
   "tags": [],
   "rating": 4.4,
   "reviews": 18,
   "gallery": [
    {
     "l": "assets/products/sugar-and-spice-bakery-box-l.webp",
     "s": "assets/products/sugar-and-spice-bakery-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-6-l.webp",
     "s": "assets/bags/bag-6-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Sugar & Spice Bakery Box — a designer template by Aminata Diallo. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "sugar-and-spice-bakery-box/"
  },
  {
   "id": "fine-jewels-green-ring-box",
   "name": "Fine Jewels Green Ring Box",
   "category": "jewellery",
   "image": {
    "l": "assets/products/fine-jewels-green-ring-box-l.webp",
    "s": "assets/products/fine-jewels-green-ring-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "kwame-mensah",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 44.7,
   "tags": [],
   "rating": 4.8,
   "reviews": 79,
   "gallery": [
    {
     "l": "assets/products/fine-jewels-green-ring-box-l.webp",
     "s": "assets/products/fine-jewels-green-ring-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Fine Jewels Green Ring Box — a designer template by Kwame Mensah. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "fine-jewels-green-ring-box/"
  },
  {
   "id": "curated-beauty-co-mailer-box",
   "name": "Curated Beauty Co. Mailer Box",
   "category": "mailer",
   "image": {
    "l": "assets/products/curated-beauty-co-mailer-box-l.webp",
    "s": "assets/products/curated-beauty-co-mailer-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "amina-yusuf",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 17.0,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.3,
   "reviews": 138,
   "gallery": [
    {
     "l": "assets/products/curated-beauty-co-mailer-box-l.webp",
     "s": "assets/products/curated-beauty-co-mailer-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Curated Beauty Co. Mailer Box — a designer template by Amina Yusuf. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "curated-beauty-co-mailer-box/"
  },
  {
   "id": "haute-abaya-black-shopping-bag",
   "name": "Haute Abaya Black Shopping Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/haute-abaya-black-shopping-bag-l.webp",
    "s": "assets/products/haute-abaya-black-shopping-bag-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "mateo-herrera",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 15.0,
   "tags": [],
   "rating": 4.8,
   "reviews": 128,
   "gallery": [
    {
     "l": "assets/products/haute-abaya-black-shopping-bag-l.webp",
     "s": "assets/products/haute-abaya-black-shopping-bag-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Haute Abaya Black Shopping Bag — a designer template by Mateo Herrera. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "haute-abaya-black-shopping-bag/"
  },
  {
   "id": "bloom-and-petal-bouquet",
   "name": "Bloom & Petal Bouquet",
   "category": "floral",
   "image": {
    "l": "assets/products/bloom-and-petal-bouquet-l.webp",
    "s": "assets/products/bloom-and-petal-bouquet-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 682
   },
   "artist": "aminata-diallo",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 31.7,
   "tags": [],
   "rating": 4.6,
   "reviews": 29,
   "gallery": [
    {
     "l": "assets/products/bloom-and-petal-bouquet-l.webp",
     "s": "assets/products/bloom-and-petal-bouquet-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 682
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Bloom & Petal Bouquet — a designer template by Aminata Diallo. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "bloom-and-petal-bouquet/"
  },
  {
   "id": "chocolate-atelier-truffle-box",
   "name": "Chocolate Atelier Truffle Box",
   "category": "food",
   "image": {
    "l": "assets/products/chocolate-atelier-truffle-box-l.webp",
    "s": "assets/products/chocolate-atelier-truffle-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 19.9,
   "tags": [],
   "rating": 4.5,
   "reviews": 118,
   "gallery": [
    {
     "l": "assets/products/chocolate-atelier-truffle-box-l.webp",
     "s": "assets/products/chocolate-atelier-truffle-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Chocolate Atelier Truffle Box — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "chocolate-atelier-truffle-box/"
  },
  {
   "id": "cafe-noir-coffee-cups",
   "name": "Cafe Noir Coffee Cups",
   "category": "food",
   "image": {
    "l": "assets/products/cafe-noir-coffee-cups-l.webp",
    "s": "assets/products/cafe-noir-coffee-cups-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "kenji-sato",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 20.4,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.8,
   "reviews": 134,
   "gallery": [
    {
     "l": "assets/products/cafe-noir-coffee-cups-l.webp",
     "s": "assets/products/cafe-noir-coffee-cups-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-6-l.webp",
     "s": "assets/bags/bag-6-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Cafe Noir Coffee Cups — a designer template by Kenji Sato. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cafe-noir-coffee-cups/"
  },
  {
   "id": "elara-cosmetics-perfume-set",
   "name": "Elara Cosmetics Perfume Set",
   "category": "beauty",
   "image": {
    "l": "assets/products/elara-cosmetics-perfume-set-l.webp",
    "s": "assets/products/elara-cosmetics-perfume-set-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 15.1,
   "tags": [
    "trending"
   ],
   "rating": 4.8,
   "reviews": 180,
   "gallery": [
    {
     "l": "assets/products/elara-cosmetics-perfume-set-l.webp",
     "s": "assets/products/elara-cosmetics-perfume-set-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-1-l.webp",
     "s": "assets/bags/bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Elara Cosmetics Perfume Set — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "elara-cosmetics-perfume-set/"
  },
  {
   "id": "personalized-stationery-set",
   "name": "Personalized Stationery Set",
   "category": "stationery",
   "image": {
    "l": "assets/products/personalized-stationery-set-l.webp",
    "s": "assets/products/personalized-stationery-set-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 683
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 26.5,
   "tags": [
    "trending"
   ],
   "rating": 4.4,
   "reviews": 173,
   "gallery": [
    {
     "l": "assets/products/personalized-stationery-set-l.webp",
     "s": "assets/products/personalized-stationery-set-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 683
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Personalized Stationery Set — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-stationery-set/"
  },
  {
   "id": "luxury-paper-gift-bag",
   "name": "Luxury Paper Gift Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/luxury-paper-gift-bag-l.webp",
    "s": "assets/products/luxury-paper-gift-bag-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "amina-yusuf",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 6.6,
   "tags": [],
   "rating": 4.5,
   "reviews": 148,
   "gallery": [
    {
     "l": "assets/products/luxury-paper-gift-bag-l.webp",
     "s": "assets/products/luxury-paper-gift-bag-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-1-l.webp",
     "s": "assets/bags/bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Luxury Paper Gift Bag — a designer template by Amina Yusuf. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-paper-gift-bag/"
  },
  {
   "id": "personalized-magnetic-box",
   "name": "Personalized Magnetic Box",
   "category": "boxes",
   "image": {
    "l": "assets/products/personalized-magnetic-box-l.webp",
    "s": "assets/products/personalized-magnetic-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 15.3,
   "tags": [
    "hot"
   ],
   "rating": 4.7,
   "reviews": 177,
   "gallery": [
    {
     "l": "assets/products/personalized-magnetic-box-l.webp",
     "s": "assets/products/personalized-magnetic-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-1-l.webp",
     "s": "assets/bags/bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Personalized Magnetic Box — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-magnetic-box/"
  },
  {
   "id": "custom-printed-cardboard-mailer-box",
   "name": "Custom Printed Cardboard Mailer Box",
   "category": "mailer",
   "image": {
    "l": "assets/products/custom-printed-cardboard-mailer-box-l.webp",
    "s": "assets/products/custom-printed-cardboard-mailer-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "aminata-diallo",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 14.0,
   "tags": [
    "trending",
    "editors"
   ],
   "rating": 4.3,
   "reviews": 80,
   "gallery": [
    {
     "l": "assets/products/custom-printed-cardboard-mailer-box-l.webp",
     "s": "assets/products/custom-printed-cardboard-mailer-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Custom Printed Cardboard Mailer Box — a designer template by Aminata Diallo. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-printed-cardboard-mailer-box/"
  },
  {
   "id": "cosmetic-tube",
   "name": "Cosmetic Tube",
   "category": "tubes",
   "image": {
    "l": "assets/products/cosmetic-tube-l.webp",
    "s": "assets/products/cosmetic-tube-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "mateo-herrera",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 11.0,
   "tags": [],
   "rating": 4.9,
   "reviews": 132,
   "gallery": [
    {
     "l": "assets/products/cosmetic-tube-l.webp",
     "s": "assets/products/cosmetic-tube-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-2-l.webp",
     "s": "assets/bags/bag-2-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Cosmetic Tube — a designer template by Mateo Herrera. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cosmetic-tube/"
  },
  {
   "id": "bakery-box",
   "name": "Bakery Box",
   "category": "food",
   "image": {
    "l": "assets/products/bakery-box-l.webp",
    "s": "assets/products/bakery-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "kenji-sato",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 16.6,
   "tags": [],
   "rating": 4.7,
   "reviews": 149,
   "gallery": [
    {
     "l": "assets/products/bakery-box-l.webp",
     "s": "assets/products/bakery-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-10-l.webp",
     "s": "assets/bags/bag-10-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Bakery Box — a designer template by Kenji Sato. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "bakery-box/"
  },
  {
   "id": "luxury-flower-bouquet-box",
   "name": "Luxury Flower Bouquet Box",
   "category": "floral",
   "image": {
    "l": "assets/products/luxury-flower-bouquet-box-l.webp",
    "s": "assets/products/luxury-flower-bouquet-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 38.5,
   "tags": [
    "new"
   ],
   "rating": 4.8,
   "reviews": 105,
   "gallery": [
    {
     "l": "assets/products/luxury-flower-bouquet-box-l.webp",
     "s": "assets/products/luxury-flower-bouquet-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-12-l.webp",
     "s": "assets/bags/bag-12-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Luxury Flower Bouquet Box — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-flower-bouquet-box/"
  },
  {
   "id": "jewelry-keepsake-box",
   "name": "Jewelry Keepsake Box",
   "category": "jewellery",
   "image": {
    "l": "assets/products/jewelry-keepsake-box-l.webp",
    "s": "assets/products/jewelry-keepsake-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "kwame-mensah",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 55.7,
   "tags": [
    "new"
   ],
   "rating": 4.3,
   "reviews": 161,
   "gallery": [
    {
     "l": "assets/products/jewelry-keepsake-box-l.webp",
     "s": "assets/products/jewelry-keepsake-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-13-l.webp",
     "s": "assets/bags/bag-13-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-4-l.webp",
     "s": "assets/bags/bag-4-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Jewelry Keepsake Box — a designer template by Kwame Mensah. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "jewelry-keepsake-box/"
  },
  {
   "id": "custom-designed-folding-carton",
   "name": "Custom Designed Folding Carton",
   "category": "boxes",
   "image": {
    "l": "assets/products/custom-designed-folding-carton-l.webp",
    "s": "assets/products/custom-designed-folding-carton-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "henrik-sorensen",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 41.4,
   "tags": [],
   "rating": 4.3,
   "reviews": 33,
   "gallery": [
    {
     "l": "assets/products/custom-designed-folding-carton-l.webp",
     "s": "assets/products/custom-designed-folding-carton-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-3-l.webp",
     "s": "assets/bags/bag-3-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Custom Designed Folding Carton — a designer template by Henrik Sørensen. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-designed-folding-carton/"
  },
  {
   "id": "personalized-stationery-set-2",
   "name": "Personalized Stationery Set 2",
   "category": "stationery",
   "image": {
    "l": "assets/products/personalized-stationery-set-2-l.webp",
    "s": "assets/products/personalized-stationery-set-2-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "priya-nair",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 23.2,
   "tags": [
    "bestseller",
    "editors"
   ],
   "rating": 4.9,
   "reviews": 187,
   "gallery": [
    {
     "l": "assets/products/personalized-stationery-set-2-l.webp",
     "s": "assets/products/personalized-stationery-set-2-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-8-l.webp",
     "s": "assets/bags/bag-8-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Personalized Stationery Set 2 — a designer template by Priya Nair. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-stationery-set-2/"
  },
  {
   "id": "premium-rigid-chocolate-box",
   "name": "Premium Rigid Chocolate Box",
   "category": "food",
   "image": {
    "l": "assets/products/premium-rigid-chocolate-box-l.webp",
    "s": "assets/products/premium-rigid-chocolate-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "hana-lee",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 18.9,
   "tags": [
    "trending"
   ],
   "rating": 4.6,
   "reviews": 115,
   "gallery": [
    {
     "l": "assets/products/premium-rigid-chocolate-box-l.webp",
     "s": "assets/products/premium-rigid-chocolate-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-6-l.webp",
     "s": "assets/bags/bag-6-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-5-l.webp",
     "s": "assets/bags/bag-5-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Premium Rigid Chocolate Box — a designer template by Hana Lee. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "premium-rigid-chocolate-box/"
  },
  {
   "id": "custom-branded-garment-bag",
   "name": "Custom Branded Garment Bag",
   "category": "bags",
   "image": {
    "l": "assets/products/custom-branded-garment-bag-l.webp",
    "s": "assets/products/custom-branded-garment-bag-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "amina-yusuf",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 14.6,
   "tags": [
    "bestseller"
   ],
   "rating": 4.7,
   "reviews": 45,
   "gallery": [
    {
     "l": "assets/products/custom-branded-garment-bag-l.webp",
     "s": "assets/products/custom-branded-garment-bag-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-11-l.webp",
     "s": "assets/bags/bag-11-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Custom Branded Garment Bag — a designer template by Amina Yusuf. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-branded-garment-bag/"
  },
  {
   "id": "luxury-candle-gift-box",
   "name": "Luxury Candle Gift Box",
   "category": "beauty",
   "image": {
    "l": "assets/products/luxury-candle-gift-box-l.webp",
    "s": "assets/products/luxury-candle-gift-box-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 568
   },
   "artist": "yasmin-al-najjar",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 33.9,
   "tags": [
    "trending"
   ],
   "rating": 4.3,
   "reviews": 109,
   "gallery": [
    {
     "l": "assets/products/luxury-candle-gift-box-l.webp",
     "s": "assets/products/luxury-candle-gift-box-s.webp",
     "lw": 512,
     "sw": 480,
     "h": 568
    },
    {
     "l": "assets/bags/bag-1-l.webp",
     "s": "assets/bags/bag-1-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    },
    {
     "l": "assets/bags/bag-7-l.webp",
     "s": "assets/bags/bag-7-s.webp",
     "lw": 1200,
     "sw": 480,
     "h": 723
    }
   ],
   "featured": false,
   "blurb": "Luxury Candle Gift Box — a designer template by Yasmin Al-Najjar. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-candle-gift-box/"
  }
 ],
 "artists": [
  {
   "id": "aminata-diallo",
   "name": "Aminata Diallo",
   "studio": "Atelier Sahel",
   "country": "SN",
   "flag": "🇸🇳",
   "style": "Heritage Textile",
   "styleTags": [
    "kraft",
    "natural",
    "neutral",
    "taupe",
    "woodland",
    "botanical",
    "earth"
   ],
   "bio": "Aminata translates West-African textile heritage — mudcloth geometry, indigo and warm earth tones — into modern, tactile packaging.",
   "avatar": {
    "l": "assets/artists/aminata-diallo-l.webp",
    "s": "assets/artists/aminata-diallo-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "since": 2019,
   "followers": 6245,
   "products": [
    "kraft-mailer-box-gold-emblem",
    "black-patterned-mailer-box",
    "sugar-and-spice-bakery-box",
    "bloom-and-petal-bouquet",
    "custom-printed-cardboard-mailer-box"
   ],
   "collections": [
    "neutral-taupe-botanical",
    "woodland-botanical-cream",
    "kraft-gray-natural"
   ],
   "rating": 4.5
  },
  {
   "id": "kenji-sato",
   "name": "Kenji Sato",
   "studio": "Studio Sumi",
   "country": "JP",
   "flag": "🇯🇵",
   "style": "Quiet Line Work",
   "styleTags": [
    "minimal",
    "white",
    "silver",
    "clean",
    "illustrated",
    "line",
    "fox"
   ],
   "bio": "Kenji draws in fine ink lines and negative space — restrained, botanical-leaning illustration with a calm Japanese sensibility.",
   "avatar": {
    "l": "assets/artists/kenji-sato-l.webp",
    "s": "assets/artists/kenji-sato-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 683
   },
   "since": 2019,
   "followers": 5114,
   "products": [
    "white-cake-box",
    "white-window-gift-box-ribbon",
    "ivory-cube-favor-boxes",
    "cafe-noir-coffee-cups",
    "bakery-box"
   ],
   "collections": [
    "floral-fox-woodland",
    "white-silver-minimal",
    "sage-wildflower-illustrated"
   ],
   "rating": 4.9
  },
  {
   "id": "priya-nair",
   "name": "Priya Nair",
   "studio": "Marigold Studio",
   "country": "IN",
   "flag": "🇮🇳",
   "style": "Vibrant Floral",
   "styleTags": [
    "floral",
    "blush",
    "pink",
    "sage",
    "soft",
    "vibrant",
    "botanical",
    "wildflower"
   ],
   "bio": "Priya bursts with colour — marigolds, paisley and joyful florals from South-Indian craft, tuned for celebration and gifting.",
   "avatar": {
    "l": "assets/artists/priya-nair-l.webp",
    "s": "assets/artists/priya-nair-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "since": 2017,
   "followers": 7491,
   "products": [
    "blush-pink-round-gift-box",
    "black-perfume-box",
    "blush-pink-bouquet-wrap",
    "elara-cosmetics-perfume-set",
    "luxury-flower-bouquet-box",
    "personalized-stationery-set-2"
   ],
   "collections": [
    "blush-kraft-natural",
    "blush-pink-floral",
    "sage-blush-floral"
   ],
   "rating": 4.6
  },
  {
   "id": "mateo-herrera",
   "name": "Mateo Herrera",
   "studio": "Taller Herrera",
   "country": "MX",
   "flag": "🇲🇽",
   "style": "Folk Maximalist",
   "styleTags": [
    "abstract",
    "multicolor",
    "vibrant",
    "playful",
    "bold",
    "colorful"
   ],
   "bio": "Mateo is loud and proud — saturated folk-art colour blocks and papel-picado energy that leap off the shelf.",
   "avatar": {
    "l": "assets/artists/mateo-herrera-l.webp",
    "s": "assets/artists/mateo-herrera-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 682
   },
   "since": 2022,
   "followers": 3333,
   "products": [
    "black-garment-bag",
    "terracotta-cylinder-tube",
    "haute-abaya-black-shopping-bag",
    "cosmetic-tube"
   ],
   "collections": [
    "playful-abstract-multicolor",
    "bold-abstract-colorful"
   ],
   "rating": 4.8
  },
  {
   "id": "yasmin-al-najjar",
   "name": "Yasmin Al-Najjar",
   "studio": "Najma Studio",
   "country": "AE",
   "flag": "🇦🇪",
   "style": "Arabesque",
   "styleTags": [
    "moroccan",
    "arabesque",
    "navy",
    "copper",
    "tin",
    "ornate",
    "gold",
    "geometric"
   ],
   "bio": "Yasmin builds tessellating Khaleeji geometry — zellige stars, gold lattices and arabesque borders that wrap seamlessly.",
   "avatar": {
    "l": "assets/artists/yasmin-al-najjar-l.webp",
    "s": "assets/artists/yasmin-al-najjar-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 682
   },
   "since": 2019,
   "followers": 9706,
   "products": [
    "honeyloom-gift-bag",
    "gold-mandala-paper-gift-bag",
    "ivory-gold-ornate-book-box",
    "navy-velvet-ring-box",
    "navy-tall-bottle-box",
    "artisan-coffee-green-tin",
    "luxury-candle-gift-box"
   ],
   "collections": [
    "navy-copper-moroccan",
    "navy-copper-moroccan-tin"
   ],
   "rating": 4.6
  },
  {
   "id": "henrik-sorensen",
   "name": "Henrik Sørensen",
   "studio": "Linea Nord",
   "country": "DK",
   "flag": "🇩🇰",
   "style": "Scandinavian Minimal",
   "styleTags": [
    "minimal",
    "white",
    "silver",
    "clean",
    "kraft",
    "neutral",
    "gray"
   ],
   "bio": "Henrik designs in a whisper — bone, brushed silver and uncoated kraft with one deliberate mark. Packaging that lets the product speak.",
   "avatar": {
    "l": "assets/artists/henrik-sorensen-l.webp",
    "s": "assets/artists/henrik-sorensen-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 682
   },
   "since": 2016,
   "followers": 4916,
   "products": [
    "coffee-cup",
    "kraft-cylinder-tube",
    "cream-ribbon-magnetic-gift-box",
    "gray-garment-bag",
    "personalized-stationery-set",
    "personalized-magnetic-box",
    "custom-designed-folding-carton"
   ],
   "collections": [
    "cream-kraft-minimal",
    "white-gold-minimal",
    "gray-kraft-mailer"
   ],
   "rating": 4.6
  },
  {
   "id": "amina-yusuf",
   "name": "Amina Yusuf",
   "studio": "Lagos Colour Lab",
   "country": "NG",
   "flag": "🇳🇬",
   "style": "Bold Abstract",
   "styleTags": [
    "abstract",
    "multicolor",
    "vibrant",
    "bold",
    "colorful",
    "playful"
   ],
   "bio": "Amina channels Lagos energy — bold abstract colour and pattern with fearless contrast, made to be seen across a room.",
   "avatar": {
    "l": "assets/artists/amina-yusuf-l.webp",
    "s": "assets/artists/amina-yusuf-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "since": 2018,
   "followers": 9106,
   "products": [
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "curated-beauty-co-mailer-box",
    "luxury-paper-gift-bag",
    "custom-branded-garment-bag"
   ],
   "collections": [
    "vibrant-multicolor-abstract"
   ],
   "rating": 4.6
  },
  {
   "id": "hana-lee",
   "name": "Hana Lee",
   "studio": "Seoul Atelier",
   "country": "KR",
   "flag": "🇰🇷",
   "style": "Emerald Deco",
   "styleTags": [
    "deco",
    "geometric",
    "diamond",
    "copper",
    "emerald",
    "gold",
    "teal",
    "chocolate"
   ],
   "bio": "Hana pairs jewel-toned emerald and teal with warm gold foil — crisp deco geometry for confectionery and fine fragrance.",
   "avatar": {
    "l": "assets/artists/hana-lee-l.webp",
    "s": "assets/artists/hana-lee-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 683
   },
   "since": 2021,
   "followers": 9992,
   "products": [
    "navy-gold-floral-rigid-box",
    "ivory-jewelry-box-velvet",
    "dark-chocolate-truffle-box",
    "black-perfume-drawer-box",
    "chocolate-atelier-truffle-box",
    "premium-rigid-chocolate-box"
   ],
   "collections": [
    "teal-gold-geometric",
    "emerald-gold-deco-chocolate",
    "emerald-copper-deco"
   ],
   "rating": 4.7
  },
  {
   "id": "kwame-mensah",
   "name": "Kwame Mensah",
   "studio": "Accra Geometric",
   "country": "GH",
   "flag": "🇬🇭",
   "style": "Geometric Luxe",
   "styleTags": [
    "geometric",
    "charcoal",
    "diamond",
    "burgundy"
   ],
   "bio": "Kwame fuses kente-inspired geometry with deep luxe palettes — charcoal, burgundy and gold for jewellery, spirits and couture.",
   "avatar": {
    "l": "assets/artists/kwame-mensah-l.webp",
    "s": "assets/artists/kwame-mensah-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "since": 2021,
   "followers": 2159,
   "products": [
    "burgundy-chocolate-gift-box",
    "green-geometric-paper-gift-bag",
    "burgundy-rigid-lid-box",
    "fine-jewels-green-ring-box",
    "jewelry-keepsake-box"
   ],
   "collections": [
    "ivory-gold-lotus-luxury",
    "charcoal-copper-geometric",
    "charcoal-copper-diamond",
    "burgundy-gold-ornate",
    "black-burgundy-gold-luxury"
   ],
   "rating": 4.9
  }
 ],
 "makers": [
  {
   "id": "imprint-atelier",
   "name": "Imprint Atelier",
   "country": "AE",
   "flag": "🇦🇪",
   "color": "#1a1a1a",
   "rating": 4.9,
   "leadDays": 7,
   "priceMul": 1.0,
   "moq": 250,
   "since": 2017,
   "reviews": 412,
   "capabilities": [
    "Offset + digital",
    "Foil & emboss",
    "Rigid box assembly",
    "Eco inks"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®",
    "ISO 9001",
    "G7 Master"
   ],
   "bio": "Imprint's flagship atelier in Dubai — the house standard for foil, emboss and rigid-box finishing, and the default for featured templates.",
   "products": [
    "honeyloom-gift-bag",
    "coffee-cup",
    "gold-mandala-paper-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "burgundy-chocolate-gift-box",
    "kraft-mailer-box-gold-emblem",
    "white-cake-box",
    "kraft-cylinder-tube",
    "blush-pink-round-gift-box",
    "ivory-jewelry-box-velvet",
    "black-garment-bag",
    "black-perfume-box",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "cream-ribbon-magnetic-gift-box",
    "black-patterned-mailer-box",
    "navy-velvet-ring-box",
    "white-window-gift-box-ribbon",
    "terracotta-cylinder-tube",
    "burgundy-rigid-lid-box",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "black-perfume-drawer-box",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "fine-jewels-green-ring-box",
    "curated-beauty-co-mailer-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "elara-cosmetics-perfume-set",
    "personalized-stationery-set",
    "luxury-paper-gift-bag",
    "personalized-magnetic-box",
    "custom-printed-cardboard-mailer-box",
    "cosmetic-tube",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "jewelry-keepsake-box",
    "custom-designed-folding-carton",
    "personalized-stationery-set-2",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "gulf-print",
   "name": "Gulf Print Works",
   "country": "AE",
   "flag": "🇦🇪",
   "color": "#0f6e63",
   "rating": 4.6,
   "leadDays": 9,
   "priceMul": 0.92,
   "moq": 500,
   "since": 2009,
   "reviews": 318,
   "capabilities": [
    "High-volume offset",
    "Litho-lam",
    "Window patching"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil"
   ],
   "certs": [
    "FSC®",
    "ISO 9001"
   ],
   "bio": "A Sharjah high-volume house — sharp pricing at scale for retail rollouts and seasonal campaigns.",
   "products": [
    "coffee-cup",
    "gold-mandala-paper-gift-bag",
    "burgundy-chocolate-gift-box",
    "kraft-mailer-box-gold-emblem",
    "white-cake-box",
    "kraft-cylinder-tube",
    "black-garment-bag",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "black-patterned-mailer-box",
    "terracotta-cylinder-tube",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "curated-beauty-co-mailer-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "personalized-stationery-set",
    "luxury-paper-gift-bag",
    "custom-printed-cardboard-mailer-box",
    "cosmetic-tube",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "personalized-stationery-set-2",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag"
   ]
  },
  {
   "id": "najm-packaging",
   "name": "Najm Packaging",
   "country": "SA",
   "flag": "🇸🇦",
   "color": "#1f7a5a",
   "rating": 4.7,
   "leadDays": 8,
   "priceMul": 1.04,
   "moq": 300,
   "since": 2014,
   "reviews": 276,
   "capabilities": [
    "Rigid & magnetic boxes",
    "Velvet lining",
    "Soft-touch lam"
   ],
   "finishes": [
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "ISO 9001",
    "ISO 14001"
   ],
   "bio": "Riyadh specialists in rigid and jewellery boxes — magnetic closures, velvet inserts and flawless wraps.",
   "products": [
    "honeyloom-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "blush-pink-round-gift-box",
    "ivory-jewelry-box-velvet",
    "black-perfume-box",
    "cream-ribbon-magnetic-gift-box",
    "navy-velvet-ring-box",
    "white-window-gift-box-ribbon",
    "burgundy-rigid-lid-box",
    "black-perfume-drawer-box",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "fine-jewels-green-ring-box",
    "elara-cosmetics-perfume-set",
    "personalized-magnetic-box",
    "jewelry-keepsake-box",
    "custom-designed-folding-carton",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "levant-press",
   "name": "Levant Press",
   "country": "LB",
   "flag": "🇱🇧",
   "color": "#b87333",
   "rating": 4.5,
   "leadDays": 12,
   "priceMul": 0.97,
   "moq": 200,
   "since": 2005,
   "reviews": 201,
   "capabilities": [
    "Artisan letterpress",
    "Hand assembly",
    "Specialty papers"
   ],
   "finishes": [
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®"
   ],
   "bio": "A Beirut craft press — letterpress, hand-assembly and specialty stock for small, beautiful runs.",
   "products": [
    "gold-mandala-paper-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "burgundy-chocolate-gift-box",
    "white-cake-box",
    "blush-pink-round-gift-box",
    "black-garment-bag",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "cream-ribbon-magnetic-gift-box",
    "white-window-gift-box-ribbon",
    "burgundy-rigid-lid-box",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "luxury-paper-gift-bag",
    "personalized-magnetic-box",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "custom-designed-folding-carton",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag"
   ]
  },
  {
   "id": "crescent-press",
   "name": "Crescent Press",
   "country": "SA",
   "flag": "🇸🇦",
   "color": "#7a2738",
   "rating": 4.8,
   "leadDays": 10,
   "priceMul": 1.08,
   "moq": 150,
   "since": 2019,
   "reviews": 164,
   "capabilities": [
    "Luxury rigid",
    "UV spot",
    "Multi-level emboss",
    "Edge painting"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®",
    "ISO 9001",
    "Sedex"
   ],
   "bio": "Jeddah's luxury-only line — UV spot, sculpted multi-level emboss and painted edges for couture and fragrance.",
   "products": [
    "honeyloom-gift-bag",
    "ivory-jewelry-box-velvet",
    "black-perfume-box",
    "navy-velvet-ring-box",
    "black-perfume-drawer-box",
    "fine-jewels-green-ring-box",
    "elara-cosmetics-perfume-set",
    "jewelry-keepsake-box",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "marina-pack",
   "name": "Marina Pack",
   "country": "QA",
   "flag": "🇶🇦",
   "color": "#2a3a5a",
   "rating": 4.4,
   "leadDays": 11,
   "priceMul": 0.95,
   "moq": 400,
   "since": 2012,
   "reviews": 148,
   "capabilities": [
    "Corrugated & mailers",
    "Flexo print",
    "Recycled board",
    "Mono-material"
   ],
   "finishes": [
    "Matte",
    "Kraft",
    "Foil"
   ],
   "certs": [
    "FSC®",
    "ISO 14001"
   ],
   "bio": "Doha's sustainability-forward mailer house — recycled, mono-material and plastic-free e-commerce packaging.",
   "products": [
    "coffee-cup",
    "kraft-mailer-box-gold-emblem",
    "black-patterned-mailer-box",
    "curated-beauty-co-mailer-box",
    "custom-printed-cardboard-mailer-box"
   ]
  }
 ],
 "collections": [
  {
   "id": "playful-abstract-multicolor",
   "name": "Playful Abstract Multicolor",
   "image": {
    "l": "assets/collections/playful-abstract-multicolor-l.webp",
    "s": "assets/collections/playful-abstract-multicolor-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "artist": "mateo-herrera",
   "accent": "#e0556b",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "ivory-gold-lotus-luxury",
   "name": "Ivory Gold Lotus Luxury",
   "image": {
    "l": "assets/collections/ivory-gold-lotus-luxury-l.webp",
    "s": "assets/collections/ivory-gold-lotus-luxury-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 683
   },
   "artist": "kwame-mensah",
   "accent": "#c79a63",
   "items": 6,
   "tags": []
  },
  {
   "id": "floral-fox-woodland",
   "name": "Floral Fox Woodland",
   "image": {
    "l": "assets/collections/floral-fox-woodland-l.webp",
    "s": "assets/collections/floral-fox-woodland-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "artist": "kenji-sato",
   "accent": "#cf7a92",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "teal-gold-geometric",
   "name": "Teal Gold Geometric",
   "image": {
    "l": "assets/collections/teal-gold-geometric-l.webp",
    "s": "assets/collections/teal-gold-geometric-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 682
   },
   "artist": "hana-lee",
   "accent": "#c79a63",
   "items": 12,
   "tags": []
  },
  {
   "id": "emerald-gold-deco-chocolate",
   "name": "Emerald Gold Deco Chocolate",
   "image": {
    "l": "assets/collections/emerald-gold-deco-chocolate-l.webp",
    "s": "assets/collections/emerald-gold-deco-chocolate-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 682
   },
   "artist": "hana-lee",
   "accent": "#c79a63",
   "items": 10,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "cream-kraft-minimal",
   "name": "Cream Kraft Minimal",
   "image": {
    "l": "assets/collections/cream-kraft-minimal-l.webp",
    "s": "assets/collections/cream-kraft-minimal-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 682
   },
   "artist": "henrik-sorensen",
   "accent": "#b9996a",
   "items": 6,
   "tags": []
  },
  {
   "id": "blush-kraft-natural",
   "name": "Blush Kraft Natural",
   "image": {
    "l": "assets/collections/blush-kraft-natural-l.webp",
    "s": "assets/collections/blush-kraft-natural-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "artist": "priya-nair",
   "accent": "#b9996a",
   "items": 13,
   "tags": []
  },
  {
   "id": "emerald-copper-deco",
   "name": "Emerald Copper Deco",
   "image": {
    "l": "assets/collections/emerald-copper-deco-l.webp",
    "s": "assets/collections/emerald-copper-deco-s.webp",
    "lw": 682,
    "sw": 480,
    "h": 683
   },
   "artist": "hana-lee",
   "accent": "#1f7a5a",
   "items": 7,
   "tags": []
  },
  {
   "id": "neutral-taupe-botanical",
   "name": "Neutral Taupe Botanical",
   "image": {
    "l": "assets/collections/neutral-taupe-botanical-l.webp",
    "s": "assets/collections/neutral-taupe-botanical-s.webp",
    "lw": 683,
    "sw": 480,
    "h": 683
   },
   "artist": "aminata-diallo",
   "accent": "#7a8a6a",
   "items": 11,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "white-gold-minimal",
   "name": "White Gold Minimal",
   "image": {
    "l": "assets/collections/white-gold-minimal-l.webp",
    "s": "assets/collections/white-gold-minimal-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "henrik-sorensen",
   "accent": "#c79a63",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "woodland-botanical-cream",
   "name": "Woodland Botanical Cream",
   "image": {
    "l": "assets/collections/woodland-botanical-cream-l.webp",
    "s": "assets/collections/woodland-botanical-cream-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "aminata-diallo",
   "accent": "#8a6b4a",
   "items": 12,
   "tags": []
  },
  {
   "id": "charcoal-copper-geometric",
   "name": "Charcoal Copper Geometric",
   "image": {
    "l": "assets/collections/charcoal-copper-geometric-l.webp",
    "s": "assets/collections/charcoal-copper-geometric-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kwame-mensah",
   "accent": "#4a4a52",
   "items": 6,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "bold-abstract-colorful",
   "name": "Bold Abstract Colorful",
   "image": {
    "l": "assets/collections/bold-abstract-colorful-l.webp",
    "s": "assets/collections/bold-abstract-colorful-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "mateo-herrera",
   "accent": "#e0556b",
   "items": 10,
   "tags": []
  },
  {
   "id": "white-silver-minimal",
   "name": "White Silver Minimal",
   "image": {
    "l": "assets/collections/white-silver-minimal-l.webp",
    "s": "assets/collections/white-silver-minimal-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kenji-sato",
   "accent": "#9a958c",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "sage-wildflower-illustrated",
   "name": "Sage Wildflower Illustrated",
   "image": {
    "l": "assets/collections/sage-wildflower-illustrated-l.webp",
    "s": "assets/collections/sage-wildflower-illustrated-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kenji-sato",
   "accent": "#8a9a7a",
   "items": 10,
   "tags": []
  },
  {
   "id": "charcoal-copper-diamond",
   "name": "Charcoal Copper Diamond",
   "image": {
    "l": "assets/collections/charcoal-copper-diamond-l.webp",
    "s": "assets/collections/charcoal-copper-diamond-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kwame-mensah",
   "accent": "#4a4a52",
   "items": 8,
   "tags": []
  },
  {
   "id": "vibrant-multicolor-abstract",
   "name": "Vibrant Multicolor Abstract",
   "image": {
    "l": "assets/collections/vibrant-multicolor-abstract-l.webp",
    "s": "assets/collections/vibrant-multicolor-abstract-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "amina-yusuf",
   "accent": "#e0556b",
   "items": 6,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "burgundy-gold-ornate",
   "name": "Burgundy Gold Ornate",
   "image": {
    "l": "assets/collections/burgundy-gold-ornate-l.webp",
    "s": "assets/collections/burgundy-gold-ornate-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kwame-mensah",
   "accent": "#c79a63",
   "items": 15,
   "tags": []
  },
  {
   "id": "blush-pink-floral",
   "name": "Blush Pink Floral",
   "image": {
    "l": "assets/collections/blush-pink-floral-l.webp",
    "s": "assets/collections/blush-pink-floral-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "priya-nair",
   "accent": "#cf7a92",
   "items": 13,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "navy-copper-moroccan",
   "name": "Navy Copper Moroccan",
   "image": {
    "l": "assets/collections/navy-copper-moroccan-l.webp",
    "s": "assets/collections/navy-copper-moroccan-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "yasmin-al-najjar",
   "accent": "#b87333",
   "items": 14,
   "tags": []
  },
  {
   "id": "gray-kraft-mailer",
   "name": "Gray Kraft Mailer",
   "image": {
    "l": "assets/collections/gray-kraft-mailer-l.webp",
    "s": "assets/collections/gray-kraft-mailer-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "henrik-sorensen",
   "accent": "#b9996a",
   "items": 10,
   "tags": []
  },
  {
   "id": "black-burgundy-gold-luxury",
   "name": "Black Burgundy Gold Luxury",
   "image": {
    "l": "assets/collections/black-burgundy-gold-luxury-l.webp",
    "s": "assets/collections/black-burgundy-gold-luxury-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "kwame-mensah",
   "accent": "#c79a63",
   "items": 7,
   "tags": []
  },
  {
   "id": "sage-blush-floral",
   "name": "Sage Blush Floral",
   "image": {
    "l": "assets/collections/sage-blush-floral-l.webp",
    "s": "assets/collections/sage-blush-floral-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "priya-nair",
   "accent": "#cf7a92",
   "items": 7,
   "tags": []
  },
  {
   "id": "navy-copper-moroccan-tin",
   "name": "Navy Copper Moroccan Tin",
   "image": {
    "l": "assets/collections/navy-copper-moroccan-tin-l.webp",
    "s": "assets/collections/navy-copper-moroccan-tin-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "yasmin-al-najjar",
   "accent": "#b87333",
   "items": 8,
   "tags": []
  },
  {
   "id": "kraft-gray-natural",
   "name": "Kraft Gray Natural",
   "image": {
    "l": "assets/collections/kraft-gray-natural-l.webp",
    "s": "assets/collections/kraft-gray-natural-s.webp",
    "lw": 512,
    "sw": 480,
    "h": 512
   },
   "artist": "aminata-diallo",
   "accent": "#b9996a",
   "items": 12,
   "tags": []
  }
 ],
 "bags": [
  {
   "l": "assets/bags/bag-1-l.webp",
   "s": "assets/bags/bag-1-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-2-l.webp",
   "s": "assets/bags/bag-2-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-3-l.webp",
   "s": "assets/bags/bag-3-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-4-l.webp",
   "s": "assets/bags/bag-4-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-5-l.webp",
   "s": "assets/bags/bag-5-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-6-l.webp",
   "s": "assets/bags/bag-6-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-7-l.webp",
   "s": "assets/bags/bag-7-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-8-l.webp",
   "s": "assets/bags/bag-8-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-9-l.webp",
   "s": "assets/bags/bag-9-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-10-l.webp",
   "s": "assets/bags/bag-10-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-11-l.webp",
   "s": "assets/bags/bag-11-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-12-l.webp",
   "s": "assets/bags/bag-12-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  },
  {
   "l": "assets/bags/bag-13-l.webp",
   "s": "assets/bags/bag-13-s.webp",
   "lw": 1200,
   "sw": 480,
   "h": 723
  }
 ]
};
