/* AUTO-GENERATED by tools/build_catalog.py — do not edit by hand. */
window.IMPRINT_CATALOG = {
 "categories": [
  {
   "id": "bags",
   "name": "Bags & Totes",
   "desc": "Luxury shopping, gift & garment bags with foil, emboss and ribbon handles."
  },
  {
   "id": "boxes",
   "name": "Rigid & Gift Boxes",
   "desc": "Magnetic, rigid lid, book and folding boxes for premium unboxing."
  },
  {
   "id": "mailer",
   "name": "Mailer & Shipping",
   "desc": "Self-locking e-commerce mailers and branded shipping cartons."
  },
  {
   "id": "food",
   "name": "Food & Gourmet",
   "desc": "Bakery, chocolate, coffee and confectionery packaging."
  },
  {
   "id": "beauty",
   "name": "Beauty & Fragrance",
   "desc": "Perfume, cosmetic and candle packaging with a jewel-like finish."
  },
  {
   "id": "jewellery",
   "name": "Jewellery & Keepsake",
   "desc": "Ring, velvet and keepsake boxes that protect and impress."
  },
  {
   "id": "tubes",
   "name": "Tubes & Cylinders",
   "desc": "Round rigid tubes for spirits, cosmetics, posters and gifting."
  },
  {
   "id": "floral",
   "name": "Floral & Bouquet",
   "desc": "Bouquet wraps and flower boxes for florists and events."
  },
  {
   "id": "stationery",
   "name": "Stationery & Cards",
   "desc": "Branded stationery sets, cards and enclosures."
  }
 ],
 "tags": {
  "hot": {
   "label": "Hot",
   "tone": "hot"
  },
  "trending": {
   "label": "Trending",
   "tone": "trend"
  },
  "new": {
   "label": "New",
   "tone": "new"
  },
  "bestseller": {
   "label": "Bestseller",
   "tone": "best"
  },
  "editors": {
   "label": "Editor's pick",
   "tone": "editor"
  },
  "eco": {
   "label": "Eco",
   "tone": "eco"
  },
  "foil": {
   "label": "Foil",
   "tone": "foil"
  },
  "limited": {
   "label": "Limited",
   "tone": "limited"
  }
 },
 "products": [
  {
   "id": "honeyloom-gift-bag",
   "name": "Honeyloom Gift Bag",
   "category": "bags",
   "image": "templates/renders/honey-gift-bag-1.jpg",
   "gallery": [
    "templates/renders/honey-gift-bag-1.jpg",
    "templates/renders/honey-gift-bag-2.jpg",
    "templates/renders/honey-gift-bag-3.jpg"
   ],
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "crescent-press",
    "najm-packaging"
   ],
   "price": 12.5,
   "tags": [
    "foil",
    "hot",
    "editors"
   ],
   "rating": 5.0,
   "reviews": 63,
   "blurb": "A foil honeycomb bottle bag with editable wordmark — the flagship Imprint template. Fully customisable in 3D.",
   "featured": true,
   "template": "honey-gift-bag",
   "href": "honeyloom-gift-bag/",
   "rich": true
  },
  {
   "id": "gold-mandala-paper-gift-bag",
   "name": "Gold Mandala Paper Gift Bag",
   "category": "bags",
   "image": "assets/products/gold-mandala-paper-gift-bag.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 8.0,
   "tags": [
    "foil",
    "trending"
   ],
   "rating": 4.3,
   "reviews": 178,
   "gallery": [
    "assets/products/gold-mandala-paper-gift-bag.png",
    "assets/bags/bag-7.jpg",
    "assets/bags/bag-10.jpg"
   ],
   "featured": false,
   "blurb": "Gold Mandala Paper Gift Bag — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "gold-mandala-paper-gift-bag/"
  },
  {
   "id": "navy-gold-floral-rigid-box",
   "name": "Navy Gold Floral Rigid Box",
   "category": "boxes",
   "image": "assets/products/navy-gold-floral-rigid-box.png",
   "artist": "hana-kim",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 23.4,
   "tags": [
    "foil"
   ],
   "rating": 4.8,
   "reviews": 39,
   "gallery": [
    "assets/products/navy-gold-floral-rigid-box.png",
    "assets/bags/bag-8.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Navy Gold Floral Rigid Box — a designer template by Hana Kim. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-gold-floral-rigid-box/"
  },
  {
   "id": "ivory-gold-ornate-book-box",
   "name": "Ivory Gold Ornate Book Box",
   "category": "boxes",
   "image": "assets/products/ivory-gold-ornate-book-box.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 34.6,
   "tags": [
    "foil",
    "bestseller"
   ],
   "rating": 4.9,
   "reviews": 27,
   "gallery": [
    "assets/products/ivory-gold-ornate-book-box.png",
    "assets/bags/bag-8.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": true,
   "blurb": "Ivory Gold Ornate Book Box — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-gold-ornate-book-box/"
  },
  {
   "id": "burgundy-chocolate-gift-box",
   "name": "Burgundy Chocolate Gift Box",
   "category": "food",
   "image": "assets/products/burgundy-chocolate-gift-box.png",
   "artist": "hana-kim",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 14.8,
   "tags": [],
   "rating": 4.9,
   "reviews": 54,
   "gallery": [
    "assets/products/burgundy-chocolate-gift-box.png",
    "assets/bags/bag-13.jpg",
    "assets/bags/bag-12.jpg"
   ],
   "featured": true,
   "blurb": "Burgundy Chocolate Gift Box — a designer template by Hana Kim. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "burgundy-chocolate-gift-box/"
  },
  {
   "id": "kraft-mailer-box-gold-emblem",
   "name": "Kraft Mailer Box Gold Emblem",
   "category": "mailer",
   "image": "assets/products/kraft-mailer-box-gold-emblem.png",
   "artist": "liam-obrien",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 7.5,
   "tags": [
    "foil",
    "eco",
    "new"
   ],
   "rating": 4.3,
   "reviews": 161,
   "gallery": [
    "assets/products/kraft-mailer-box-gold-emblem.png",
    "assets/bags/bag-8.jpg",
    "assets/bags/bag-13.jpg"
   ],
   "featured": false,
   "blurb": "Kraft Mailer Box Gold Emblem — a designer template by Liam O'Brien. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "kraft-mailer-box-gold-emblem/"
  },
  {
   "id": "white-cake-box",
   "name": "White Cake Box",
   "category": "food",
   "image": "assets/products/white-cake-box.png",
   "artist": "yuki-tanaka",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 13.2,
   "tags": [],
   "rating": 4.8,
   "reviews": 18,
   "gallery": [
    "assets/products/white-cake-box.png",
    "assets/bags/bag-2.jpg",
    "assets/bags/bag-9.jpg"
   ],
   "featured": false,
   "blurb": "White Cake Box — a designer template by Yuki Tanaka. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "white-cake-box/"
  },
  {
   "id": "kraft-cylinder-tube",
   "name": "Kraft Cylinder Tube",
   "category": "tubes",
   "image": "assets/products/kraft-cylinder-tube.png",
   "artist": "liam-obrien",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 10.3,
   "tags": [
    "eco",
    "hot",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 145,
   "gallery": [
    "assets/products/kraft-cylinder-tube.png",
    "assets/bags/bag-5.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Kraft Cylinder Tube — a designer template by Liam O'Brien. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "kraft-cylinder-tube/"
  },
  {
   "id": "blush-pink-round-gift-box",
   "name": "Blush Pink Round Gift Box",
   "category": "boxes",
   "image": "assets/products/blush-pink-round-gift-box.png",
   "artist": "amara-okafor",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 27.0,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 189,
   "gallery": [
    "assets/products/blush-pink-round-gift-box.png",
    "assets/bags/bag-4.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Blush Pink Round Gift Box — a designer template by Amara Okafor. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "blush-pink-round-gift-box/"
  },
  {
   "id": "ivory-jewelry-box-velvet",
   "name": "Ivory Jewelry Box Velvet",
   "category": "jewellery",
   "image": "assets/products/ivory-jewelry-box-velvet.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 43.5,
   "tags": [
    "new"
   ],
   "rating": 4.3,
   "reviews": 71,
   "gallery": [
    "assets/products/ivory-jewelry-box-velvet.png",
    "assets/bags/bag-3.jpg",
    "assets/bags/bag-9.jpg"
   ],
   "featured": false,
   "blurb": "Ivory Jewelry Box Velvet — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-jewelry-box-velvet/"
  },
  {
   "id": "black-garment-bag",
   "name": "Black Garment Bag",
   "category": "bags",
   "image": "assets/products/black-garment-bag.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 12.8,
   "tags": [
    "bestseller"
   ],
   "rating": 4.8,
   "reviews": 51,
   "gallery": [
    "assets/products/black-garment-bag.png",
    "assets/bags/bag-9.jpg",
    "assets/bags/bag-10.jpg"
   ],
   "featured": false,
   "blurb": "Black Garment Bag — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-garment-bag/"
  },
  {
   "id": "black-perfume-box",
   "name": "Black Perfume Box",
   "category": "beauty",
   "image": "assets/products/black-perfume-box.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 43.5,
   "tags": [
    "trending"
   ],
   "rating": 4.9,
   "reviews": 191,
   "gallery": [
    "assets/products/black-perfume-box.png",
    "assets/bags/bag-5.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": true,
   "blurb": "Black Perfume Box — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-perfume-box/"
  },
  {
   "id": "dark-chocolate-truffle-box",
   "name": "Dark Chocolate Truffle Box",
   "category": "food",
   "image": "assets/products/dark-chocolate-truffle-box.png",
   "artist": "hana-kim",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 11.8,
   "tags": [
    "hot"
   ],
   "rating": 4.5,
   "reviews": 78,
   "gallery": [
    "assets/products/dark-chocolate-truffle-box.png",
    "assets/bags/bag-2.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Dark Chocolate Truffle Box — a designer template by Hana Kim. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "dark-chocolate-truffle-box/"
  },
  {
   "id": "green-geometric-paper-gift-bag",
   "name": "Green Geometric Paper Gift Bag",
   "category": "bags",
   "image": "assets/products/green-geometric-paper-gift-bag.png",
   "artist": "elena-petrova",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 10.9,
   "tags": [
    "new"
   ],
   "rating": 4.6,
   "reviews": 65,
   "gallery": [
    "assets/products/green-geometric-paper-gift-bag.png",
    "assets/bags/bag-1.jpg",
    "assets/bags/bag-12.jpg"
   ],
   "featured": false,
   "blurb": "Green Geometric Paper Gift Bag — a designer template by Elena Petrova. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "green-geometric-paper-gift-bag/"
  },
  {
   "id": "cream-ribbon-magnetic-gift-box",
   "name": "Cream Ribbon Magnetic Gift Box",
   "category": "boxes",
   "image": "assets/products/cream-ribbon-magnetic-gift-box.png",
   "artist": "isabella-santos",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 36.4,
   "tags": [
    "hot"
   ],
   "rating": 4.3,
   "reviews": 29,
   "gallery": [
    "assets/products/cream-ribbon-magnetic-gift-box.png",
    "assets/bags/bag-6.jpg",
    "assets/bags/bag-9.jpg"
   ],
   "featured": false,
   "blurb": "Cream Ribbon Magnetic Gift Box — a designer template by Isabella Santos. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cream-ribbon-magnetic-gift-box/"
  },
  {
   "id": "black-patterned-mailer-box",
   "name": "Black Patterned Mailer Box",
   "category": "mailer",
   "image": "assets/products/black-patterned-mailer-box.png",
   "artist": "liam-obrien",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 14.1,
   "tags": [
    "new"
   ],
   "rating": 4.9,
   "reviews": 44,
   "gallery": [
    "assets/products/black-patterned-mailer-box.png",
    "assets/bags/bag-2.jpg",
    "assets/bags/bag-5.jpg"
   ],
   "featured": true,
   "blurb": "Black Patterned Mailer Box — a designer template by Liam O'Brien. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-patterned-mailer-box/"
  },
  {
   "id": "navy-velvet-ring-box",
   "name": "Navy Velvet Ring Box",
   "category": "jewellery",
   "image": "assets/products/navy-velvet-ring-box.png",
   "artist": "noor-al-rashid",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 22.0,
   "tags": [],
   "rating": 4.9,
   "reviews": 162,
   "gallery": [
    "assets/products/navy-velvet-ring-box.png",
    "assets/bags/bag-11.jpg",
    "assets/bags/bag-8.jpg"
   ],
   "featured": true,
   "blurb": "Navy Velvet Ring Box — a designer template by Noor Al-Rashid. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-velvet-ring-box/"
  },
  {
   "id": "white-window-gift-box-ribbon",
   "name": "White Window Gift Box Ribbon",
   "category": "boxes",
   "image": "assets/products/white-window-gift-box-ribbon.png",
   "artist": "yuki-tanaka",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 38.8,
   "tags": [],
   "rating": 4.8,
   "reviews": 165,
   "gallery": [
    "assets/products/white-window-gift-box-ribbon.png",
    "assets/bags/bag-2.jpg",
    "assets/bags/bag-5.jpg"
   ],
   "featured": false,
   "blurb": "White Window Gift Box Ribbon — a designer template by Yuki Tanaka. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "white-window-gift-box-ribbon/"
  },
  {
   "id": "terracotta-cylinder-tube",
   "name": "Terracotta Cylinder Tube",
   "category": "tubes",
   "image": "assets/products/terracotta-cylinder-tube.png",
   "artist": "omar-farouk",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 19.7,
   "tags": [],
   "rating": 4.9,
   "reviews": 179,
   "gallery": [
    "assets/products/terracotta-cylinder-tube.png",
    "assets/bags/bag-5.jpg",
    "assets/bags/bag-2.jpg"
   ],
   "featured": true,
   "blurb": "Terracotta Cylinder Tube — a designer template by Omar Farouk. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "terracotta-cylinder-tube/"
  },
  {
   "id": "burgundy-rigid-lid-box",
   "name": "Burgundy Rigid Lid Box",
   "category": "boxes",
   "image": "assets/products/burgundy-rigid-lid-box.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 39.8,
   "tags": [
    "trending"
   ],
   "rating": 4.6,
   "reviews": 109,
   "gallery": [
    "assets/products/burgundy-rigid-lid-box.png",
    "assets/bags/bag-13.jpg",
    "assets/bags/bag-2.jpg"
   ],
   "featured": false,
   "blurb": "Burgundy Rigid Lid Box — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "burgundy-rigid-lid-box/"
  },
  {
   "id": "blush-pink-bouquet-wrap",
   "name": "Blush Pink Bouquet Wrap",
   "category": "floral",
   "image": "assets/products/blush-pink-bouquet-wrap.png",
   "artist": "amara-okafor",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 20.9,
   "tags": [
    "new"
   ],
   "rating": 4.5,
   "reviews": 187,
   "gallery": [
    "assets/products/blush-pink-bouquet-wrap.png",
    "assets/bags/bag-10.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Blush Pink Bouquet Wrap — a designer template by Amara Okafor. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "blush-pink-bouquet-wrap/"
  },
  {
   "id": "gray-garment-bag",
   "name": "Gray Garment Bag",
   "category": "bags",
   "image": "assets/products/gray-garment-bag.png",
   "artist": "liam-obrien",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 12.4,
   "tags": [
    "hot"
   ],
   "rating": 4.7,
   "reviews": 43,
   "gallery": [
    "assets/products/gray-garment-bag.png",
    "assets/bags/bag-10.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Gray Garment Bag — a designer template by Liam O'Brien. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "gray-garment-bag/"
  },
  {
   "id": "black-perfume-drawer-box",
   "name": "Black Perfume Drawer Box",
   "category": "beauty",
   "image": "assets/products/black-perfume-drawer-box.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 25.4,
   "tags": [
    "bestseller"
   ],
   "rating": 4.9,
   "reviews": 130,
   "gallery": [
    "assets/products/black-perfume-drawer-box.png",
    "assets/bags/bag-12.jpg",
    "assets/bags/bag-13.jpg"
   ],
   "featured": false,
   "blurb": "Black Perfume Drawer Box — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "black-perfume-drawer-box/"
  },
  {
   "id": "navy-tall-bottle-box",
   "name": "Navy Tall Bottle Box",
   "category": "boxes",
   "image": "assets/products/navy-tall-bottle-box.png",
   "artist": "noor-al-rashid",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 41.0,
   "tags": [
    "editors"
   ],
   "rating": 4.6,
   "reviews": 151,
   "gallery": [
    "assets/products/navy-tall-bottle-box.png",
    "assets/bags/bag-7.jpg",
    "assets/bags/bag-9.jpg"
   ],
   "featured": false,
   "blurb": "Navy Tall Bottle Box — a designer template by Noor Al-Rashid. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "navy-tall-bottle-box/"
  },
  {
   "id": "ivory-cube-favor-boxes",
   "name": "Ivory Cube Favor Boxes",
   "category": "boxes",
   "image": "assets/products/ivory-cube-favor-boxes.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 15.3,
   "tags": [
    "hot"
   ],
   "rating": 4.9,
   "reviews": 125,
   "gallery": [
    "assets/products/ivory-cube-favor-boxes.png",
    "assets/bags/bag-4.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Ivory Cube Favor Boxes — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ivory-cube-favor-boxes/"
  },
  {
   "id": "ab-monogram-navy-chocolate-box",
   "name": "AB Monogram Navy Chocolate Box",
   "category": "food",
   "image": "assets/products/ab-monogram-navy-chocolate-box.png",
   "artist": "diego-reyes",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 19.4,
   "tags": [
    "bestseller"
   ],
   "rating": 4.8,
   "reviews": 190,
   "gallery": [
    "assets/products/ab-monogram-navy-chocolate-box.png",
    "assets/bags/bag-9.jpg",
    "assets/bags/bag-3.jpg"
   ],
   "featured": false,
   "blurb": "AB Monogram Navy Chocolate Box — a designer template by Diego Reyes. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "ab-monogram-navy-chocolate-box/"
  },
  {
   "id": "la-petite-boutique-pink-bags",
   "name": "La Petite Boutique Pink Bags",
   "category": "bags",
   "image": "assets/products/la-petite-boutique-pink-bags.png",
   "artist": "sofia-marchetti",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 13.5,
   "tags": [
    "new",
    "editors"
   ],
   "rating": 4.6,
   "reviews": 39,
   "gallery": [
    "assets/products/la-petite-boutique-pink-bags.png",
    "assets/bags/bag-6.jpg",
    "assets/bags/bag-2.jpg"
   ],
   "featured": false,
   "blurb": "La Petite Boutique Pink Bags — a designer template by Sofia Marchetti. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "la-petite-boutique-pink-bags/"
  },
  {
   "id": "artisan-coffee-green-tin",
   "name": "Artisan Coffee Green Tin",
   "category": "food",
   "image": "assets/products/artisan-coffee-green-tin.png",
   "artist": "noor-al-rashid",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 10.8,
   "tags": [
    "new"
   ],
   "rating": 4.9,
   "reviews": 40,
   "gallery": [
    "assets/products/artisan-coffee-green-tin.png",
    "assets/bags/bag-12.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Artisan Coffee Green Tin — a designer template by Noor Al-Rashid. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "artisan-coffee-green-tin/"
  },
  {
   "id": "sugar-and-spice-bakery-box",
   "name": "Sugar & Spice Bakery Box",
   "category": "food",
   "image": "assets/products/sugar-and-spice-bakery-box.png",
   "artist": "isabella-santos",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 13.3,
   "tags": [],
   "rating": 4.4,
   "reviews": 18,
   "gallery": [
    "assets/products/sugar-and-spice-bakery-box.png",
    "assets/bags/bag-6.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Sugar & Spice Bakery Box — a designer template by Isabella Santos. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "sugar-and-spice-bakery-box/"
  },
  {
   "id": "fine-jewels-green-ring-box",
   "name": "Fine Jewels Green Ring Box",
   "category": "jewellery",
   "image": "assets/products/fine-jewels-green-ring-box.png",
   "artist": "elena-petrova",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 44.7,
   "tags": [],
   "rating": 4.8,
   "reviews": 79,
   "gallery": [
    "assets/products/fine-jewels-green-ring-box.png",
    "assets/bags/bag-3.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Fine Jewels Green Ring Box — a designer template by Elena Petrova. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "fine-jewels-green-ring-box/"
  },
  {
   "id": "curated-beauty-co-mailer-box",
   "name": "Curated Beauty Co. Mailer Box",
   "category": "mailer",
   "image": "assets/products/curated-beauty-co-mailer-box.png",
   "artist": "omar-farouk",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 17.0,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.3,
   "reviews": 138,
   "gallery": [
    "assets/products/curated-beauty-co-mailer-box.png",
    "assets/bags/bag-12.jpg",
    "assets/bags/bag-8.jpg"
   ],
   "featured": false,
   "blurb": "Curated Beauty Co. Mailer Box — a designer template by Omar Farouk. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "curated-beauty-co-mailer-box/"
  },
  {
   "id": "haute-abaya-black-shopping-bag",
   "name": "Haute Abaya Black Shopping Bag",
   "category": "bags",
   "image": "assets/products/haute-abaya-black-shopping-bag.png",
   "artist": "fatima-zahra",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 15.0,
   "tags": [],
   "rating": 4.8,
   "reviews": 128,
   "gallery": [
    "assets/products/haute-abaya-black-shopping-bag.png",
    "assets/bags/bag-3.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Haute Abaya Black Shopping Bag — a designer template by Fatima Zahra. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "haute-abaya-black-shopping-bag/"
  },
  {
   "id": "bloom-and-petal-bouquet",
   "name": "Bloom & Petal Bouquet",
   "category": "floral",
   "image": "assets/products/bloom-and-petal-bouquet.png",
   "artist": "sofia-marchetti",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 31.7,
   "tags": [],
   "rating": 4.6,
   "reviews": 29,
   "gallery": [
    "assets/products/bloom-and-petal-bouquet.png",
    "assets/bags/bag-10.jpg",
    "assets/bags/bag-12.jpg"
   ],
   "featured": false,
   "blurb": "Bloom & Petal Bouquet — a designer template by Sofia Marchetti. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "bloom-and-petal-bouquet/"
  },
  {
   "id": "chocolate-atelier-truffle-box",
   "name": "Chocolate Atelier Truffle Box",
   "category": "food",
   "image": "assets/products/chocolate-atelier-truffle-box.png",
   "artist": "hana-kim",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 19.9,
   "tags": [],
   "rating": 4.5,
   "reviews": 118,
   "gallery": [
    "assets/products/chocolate-atelier-truffle-box.png",
    "assets/bags/bag-5.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Chocolate Atelier Truffle Box — a designer template by Hana Kim. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "chocolate-atelier-truffle-box/"
  },
  {
   "id": "cafe-noir-coffee-cups",
   "name": "Cafe Noir Coffee Cups",
   "category": "food",
   "image": "assets/products/cafe-noir-coffee-cups.png",
   "artist": "isabella-santos",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 20.4,
   "tags": [
    "hot",
    "editors"
   ],
   "rating": 4.8,
   "reviews": 134,
   "gallery": [
    "assets/products/cafe-noir-coffee-cups.png",
    "assets/bags/bag-6.jpg",
    "assets/bags/bag-3.jpg"
   ],
   "featured": false,
   "blurb": "Cafe Noir Coffee Cups — a designer template by Isabella Santos. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cafe-noir-coffee-cups/"
  },
  {
   "id": "elara-cosmetics-perfume-set",
   "name": "Elara Cosmetics Perfume Set",
   "category": "beauty",
   "image": "assets/products/elara-cosmetics-perfume-set.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 15.1,
   "tags": [
    "trending"
   ],
   "rating": 4.8,
   "reviews": 180,
   "gallery": [
    "assets/products/elara-cosmetics-perfume-set.png",
    "assets/bags/bag-13.jpg",
    "assets/bags/bag-1.jpg"
   ],
   "featured": false,
   "blurb": "Elara Cosmetics Perfume Set — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "elara-cosmetics-perfume-set/"
  },
  {
   "id": "personalized-stationery-set",
   "name": "Personalized Stationery Set",
   "category": "stationery",
   "image": "assets/products/personalized-stationery-set.png",
   "artist": "yuki-tanaka",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 26.5,
   "tags": [
    "trending"
   ],
   "rating": 4.4,
   "reviews": 173,
   "gallery": [
    "assets/products/personalized-stationery-set.png",
    "assets/bags/bag-13.jpg",
    "assets/bags/bag-8.jpg"
   ],
   "featured": false,
   "blurb": "Personalized Stationery Set — a designer template by Yuki Tanaka. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-stationery-set/"
  },
  {
   "id": "luxury-paper-gift-bag",
   "name": "Luxury Paper Gift Bag",
   "category": "bags",
   "image": "assets/products/luxury-paper-gift-bag.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 6.6,
   "tags": [],
   "rating": 4.5,
   "reviews": 148,
   "gallery": [
    "assets/products/luxury-paper-gift-bag.png",
    "assets/bags/bag-1.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Luxury Paper Gift Bag — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-paper-gift-bag/"
  },
  {
   "id": "personalized-magnetic-box",
   "name": "Personalized Magnetic Box",
   "category": "boxes",
   "image": "assets/products/personalized-magnetic-box.png",
   "artist": "rami-khoury",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 15.3,
   "tags": [
    "hot"
   ],
   "rating": 4.7,
   "reviews": 177,
   "gallery": [
    "assets/products/personalized-magnetic-box.png",
    "assets/bags/bag-5.jpg",
    "assets/bags/bag-1.jpg"
   ],
   "featured": false,
   "blurb": "Personalized Magnetic Box — a designer template by Rami Khoury. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-magnetic-box/"
  },
  {
   "id": "custom-printed-cardboard-mailer-box",
   "name": "Custom Printed Cardboard Mailer Box",
   "category": "mailer",
   "image": "assets/products/custom-printed-cardboard-mailer-box.png",
   "artist": "liam-obrien",
   "makers": [
    "imprint-atelier",
    "marina-pack",
    "gulf-print"
   ],
   "price": 14.0,
   "tags": [
    "trending",
    "editors"
   ],
   "rating": 4.3,
   "reviews": 80,
   "gallery": [
    "assets/products/custom-printed-cardboard-mailer-box.png",
    "assets/bags/bag-4.jpg",
    "assets/bags/bag-2.jpg"
   ],
   "featured": false,
   "blurb": "Custom Printed Cardboard Mailer Box — a designer template by Liam O'Brien. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-printed-cardboard-mailer-box/"
  },
  {
   "id": "cosmetic-tube",
   "name": "Cosmetic Tube",
   "category": "tubes",
   "image": "assets/products/cosmetic-tube.png",
   "artist": "rami-khoury",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 11.0,
   "tags": [],
   "rating": 4.9,
   "reviews": 132,
   "gallery": [
    "assets/products/cosmetic-tube.png",
    "assets/bags/bag-2.jpg",
    "assets/bags/bag-5.jpg"
   ],
   "featured": false,
   "blurb": "Cosmetic Tube — a designer template by Rami Khoury. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "cosmetic-tube/"
  },
  {
   "id": "bakery-box",
   "name": "Bakery Box",
   "category": "food",
   "image": "assets/products/bakery-box.png",
   "artist": "sofia-marchetti",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 16.6,
   "tags": [],
   "rating": 4.7,
   "reviews": 149,
   "gallery": [
    "assets/products/bakery-box.png",
    "assets/bags/bag-10.jpg",
    "assets/bags/bag-5.jpg"
   ],
   "featured": false,
   "blurb": "Bakery Box — a designer template by Sofia Marchetti. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "bakery-box/"
  },
  {
   "id": "luxury-flower-bouquet-box",
   "name": "Luxury Flower Bouquet Box",
   "category": "floral",
   "image": "assets/products/luxury-flower-bouquet-box.png",
   "artist": "sofia-marchetti",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 38.5,
   "tags": [
    "new"
   ],
   "rating": 4.8,
   "reviews": 105,
   "gallery": [
    "assets/products/luxury-flower-bouquet-box.png",
    "assets/bags/bag-12.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Luxury Flower Bouquet Box — a designer template by Sofia Marchetti. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-flower-bouquet-box/"
  },
  {
   "id": "jewelry-keepsake-box",
   "name": "Jewelry Keepsake Box",
   "category": "jewellery",
   "image": "assets/products/jewelry-keepsake-box.png",
   "artist": "elena-petrova",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 55.7,
   "tags": [
    "new"
   ],
   "rating": 4.3,
   "reviews": 161,
   "gallery": [
    "assets/products/jewelry-keepsake-box.png",
    "assets/bags/bag-13.jpg",
    "assets/bags/bag-4.jpg"
   ],
   "featured": false,
   "blurb": "Jewelry Keepsake Box — a designer template by Elena Petrova. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "jewelry-keepsake-box/"
  },
  {
   "id": "custom-designed-folding-carton",
   "name": "Custom Designed Folding Carton",
   "category": "boxes",
   "image": "assets/products/custom-designed-folding-carton.png",
   "artist": "diego-reyes",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "levant-press"
   ],
   "price": 41.4,
   "tags": [],
   "rating": 4.3,
   "reviews": 33,
   "gallery": [
    "assets/products/custom-designed-folding-carton.png",
    "assets/bags/bag-3.jpg",
    "assets/bags/bag-11.jpg"
   ],
   "featured": false,
   "blurb": "Custom Designed Folding Carton — a designer template by Diego Reyes. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-designed-folding-carton/"
  },
  {
   "id": "personalized-stationery-set-2",
   "name": "Personalized Stationery Set 2",
   "category": "stationery",
   "image": "assets/products/personalized-stationery-set-2.png",
   "artist": "yuki-tanaka",
   "makers": [
    "imprint-atelier",
    "gulf-print"
   ],
   "price": 23.2,
   "tags": [
    "bestseller",
    "editors"
   ],
   "rating": 4.9,
   "reviews": 187,
   "gallery": [
    "assets/products/personalized-stationery-set-2.png",
    "assets/bags/bag-8.jpg",
    "assets/bags/bag-8.jpg"
   ],
   "featured": false,
   "blurb": "Personalized Stationery Set 2 — a designer template by Yuki Tanaka. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "personalized-stationery-set-2/"
  },
  {
   "id": "premium-rigid-chocolate-box",
   "name": "Premium Rigid Chocolate Box",
   "category": "food",
   "image": "assets/products/premium-rigid-chocolate-box.png",
   "artist": "hana-kim",
   "makers": [
    "imprint-atelier",
    "levant-press",
    "gulf-print"
   ],
   "price": 18.9,
   "tags": [
    "trending"
   ],
   "rating": 4.6,
   "reviews": 115,
   "gallery": [
    "assets/products/premium-rigid-chocolate-box.png",
    "assets/bags/bag-6.jpg",
    "assets/bags/bag-5.jpg"
   ],
   "featured": false,
   "blurb": "Premium Rigid Chocolate Box — a designer template by Hana Kim. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "premium-rigid-chocolate-box/"
  },
  {
   "id": "custom-branded-garment-bag",
   "name": "Custom Branded Garment Bag",
   "category": "bags",
   "image": "assets/products/custom-branded-garment-bag.png",
   "artist": "rami-khoury",
   "makers": [
    "imprint-atelier",
    "gulf-print",
    "levant-press"
   ],
   "price": 14.6,
   "tags": [
    "bestseller"
   ],
   "rating": 4.7,
   "reviews": 45,
   "gallery": [
    "assets/products/custom-branded-garment-bag.png",
    "assets/bags/bag-11.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Custom Branded Garment Bag — a designer template by Rami Khoury. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "custom-branded-garment-bag/"
  },
  {
   "id": "luxury-candle-gift-box",
   "name": "Luxury Candle Gift Box",
   "category": "beauty",
   "image": "assets/products/luxury-candle-gift-box.png",
   "artist": "layla-haddad",
   "makers": [
    "imprint-atelier",
    "najm-packaging",
    "crescent-press"
   ],
   "price": 33.9,
   "tags": [
    "trending"
   ],
   "rating": 4.3,
   "reviews": 109,
   "gallery": [
    "assets/products/luxury-candle-gift-box.png",
    "assets/bags/bag-1.jpg",
    "assets/bags/bag-7.jpg"
   ],
   "featured": false,
   "blurb": "Luxury Candle Gift Box — a designer template by Layla Haddad. Locked layout; swap text, colours and social handles to make it yours.",
   "href": "luxury-candle-gift-box/"
  }
 ],
 "artists": [
  {
   "id": "layla-haddad",
   "name": "Layla Haddad",
   "studio": "Atelier Haddad",
   "country": "AE",
   "flag": "🇦🇪",
   "style": "Gilded Ornament",
   "styleTags": [
    "luxury",
    "gold",
    "ornate",
    "mandala",
    "ivory"
   ],
   "bio": "Layla turns Khaleeji ornament into modern gold-foil packaging — mandalas, lattices and lotus motifs rendered with restraint.",
   "avatar": "assets/artists/layla-haddad.png",
   "since": 2018,
   "followers": 1400,
   "products": [
    "honeyloom-gift-bag",
    "gold-mandala-paper-gift-bag",
    "ivory-jewelry-box-velvet",
    "ivory-cube-favor-boxes",
    "elara-cosmetics-perfume-set",
    "luxury-paper-gift-bag",
    "luxury-candle-gift-box"
   ],
   "collections": [
    "ivory-gold-lotus-luxury"
   ],
   "rating": 4.5
  },
  {
   "id": "yuki-tanaka",
   "name": "Yuki Tanaka",
   "studio": "Studio Mu",
   "country": "JP",
   "flag": "🇯🇵",
   "style": "Quiet Minimal",
   "styleTags": [
    "minimal",
    "white",
    "silver",
    "clean"
   ],
   "bio": "Yuki designs in negative space. White, bone and brushed silver, with a single deliberate mark — packaging that whispers.",
   "avatar": "assets/artists/yuki-tanaka.png",
   "since": 2018,
   "followers": 9024,
   "products": [
    "white-cake-box",
    "white-window-gift-box-ribbon",
    "personalized-stationery-set",
    "personalized-stationery-set-2"
   ],
   "collections": [
    "white-gold-minimal",
    "white-silver-minimal"
   ],
   "rating": 4.9
  },
  {
   "id": "omar-farouk",
   "name": "Omar Farouk",
   "studio": "Cairo Deco",
   "country": "EG",
   "flag": "🇪🇬",
   "style": "Art Deco",
   "styleTags": [
    "deco",
    "geometric",
    "diamond",
    "copper"
   ],
   "bio": "Omar revives 1920s Cairo glamour: stepped fans, diamond lattices and copper line-work with architectural precision.",
   "avatar": "assets/artists/omar-farouk.png",
   "since": 2017,
   "followers": 8589,
   "products": [
    "terracotta-cylinder-tube",
    "curated-beauty-co-mailer-box"
   ],
   "collections": [
    "charcoal-copper-geometric"
   ],
   "rating": 4.9
  },
  {
   "id": "sofia-marchetti",
   "name": "Sofia Marchetti",
   "studio": "Foglia Studio",
   "country": "IT",
   "flag": "🇮🇹",
   "style": "Botanical Ink",
   "styleTags": [
    "botanical",
    "floral",
    "woodland",
    "wildflower",
    "illustrated"
   ],
   "bio": "Sofia hand-inks ferns, wildflowers and orchard branches — heritage botanical illustration for gourmet and beauty brands.",
   "avatar": "assets/artists/sofia-marchetti.png",
   "since": 2018,
   "followers": 3138,
   "products": [
    "la-petite-boutique-pink-bags",
    "bloom-and-petal-bouquet",
    "bakery-box",
    "luxury-flower-bouquet-box"
   ],
   "collections": [
    "woodland-botanical-cream",
    "sage-wildflower-illustrated"
   ],
   "rating": 4.8
  },
  {
   "id": "noor-al-rashid",
   "name": "Noor Al-Rashid",
   "studio": "Najma Pattern Co.",
   "country": "AE",
   "flag": "🇦🇪",
   "style": "Arabesque Geo",
   "styleTags": [
    "moroccan",
    "arabesque",
    "navy",
    "copper",
    "tin"
   ],
   "bio": "Noor builds tessellating Moorish geometry — zellige stars and navy-and-copper arabesque that wraps seamlessly.",
   "avatar": "assets/artists/noor-al-rashid.png",
   "since": 2021,
   "followers": 2727,
   "products": [
    "navy-velvet-ring-box",
    "navy-tall-bottle-box",
    "artisan-coffee-green-tin"
   ],
   "collections": [
    "navy-copper-moroccan",
    "navy-copper-moroccan-tin"
   ],
   "rating": 4.7
  },
  {
   "id": "diego-reyes",
   "name": "Diego Reyes",
   "studio": "Reyes Color Lab",
   "country": "MX",
   "flag": "🇲🇽",
   "style": "Maximal Abstract",
   "styleTags": [
    "abstract",
    "multicolor",
    "vibrant",
    "playful",
    "bold",
    "colorful"
   ],
   "bio": "Diego is loud on purpose — saturated abstract colour-blocks and painterly shapes that pop on a shelf from across the room.",
   "avatar": "assets/artists/diego-reyes.png",
   "since": 2016,
   "followers": 1449,
   "products": [
    "ab-monogram-navy-chocolate-box",
    "custom-designed-folding-carton"
   ],
   "collections": [
    "playful-abstract-multicolor",
    "bold-abstract-colorful",
    "vibrant-multicolor-abstract"
   ],
   "rating": 4.9
  },
  {
   "id": "amara-okafor",
   "name": "Amara Okafor",
   "studio": "Bloom & Blush",
   "country": "NG",
   "flag": "🇳🇬",
   "style": "Soft Floral",
   "styleTags": [
    "blush",
    "pink",
    "floral",
    "sage",
    "soft"
   ],
   "bio": "Amara works in blush, sage and powder tones — soft botanical florals for bridal, beauty and boutique gifting.",
   "avatar": "assets/artists/amara-okafor.png",
   "since": 2018,
   "followers": 4528,
   "products": [
    "blush-pink-round-gift-box",
    "blush-pink-bouquet-wrap"
   ],
   "collections": [
    "blush-kraft-natural",
    "blush-pink-floral",
    "sage-blush-floral"
   ],
   "rating": 4.8
  },
  {
   "id": "liam-obrien",
   "name": "Liam O'Brien",
   "studio": "Kraft & Co.",
   "country": "IE",
   "flag": "🇮🇪",
   "style": "Natural Kraft",
   "styleTags": [
    "kraft",
    "natural",
    "neutral",
    "taupe",
    "gray",
    "mailer"
   ],
   "bio": "Liam champions honest materials — uncoated kraft, taupe and recycled board with understated typographic marks.",
   "avatar": "assets/artists/liam-obrien.png",
   "since": 2023,
   "followers": 3301,
   "products": [
    "kraft-mailer-box-gold-emblem",
    "kraft-cylinder-tube",
    "black-patterned-mailer-box",
    "gray-garment-bag",
    "custom-printed-cardboard-mailer-box"
   ],
   "collections": [
    "cream-kraft-minimal",
    "neutral-taupe-botanical",
    "gray-kraft-mailer",
    "kraft-gray-natural"
   ],
   "rating": 4.6
  },
  {
   "id": "hana-kim",
   "name": "Hana Kim",
   "studio": "Seoul Lux",
   "country": "KR",
   "flag": "🇰🇷",
   "style": "Emerald Deco",
   "styleTags": [
    "emerald",
    "deco",
    "gold",
    "chocolate"
   ],
   "bio": "Hana pairs deep emerald with warm gold foil — jewel-toned deco built for chocolate, patisserie and fine fragrance.",
   "avatar": "assets/artists/hana-kim.png",
   "since": 2017,
   "followers": 1612,
   "products": [
    "navy-gold-floral-rigid-box",
    "burgundy-chocolate-gift-box",
    "dark-chocolate-truffle-box",
    "chocolate-atelier-truffle-box",
    "premium-rigid-chocolate-box"
   ],
   "collections": [
    "emerald-gold-deco-chocolate",
    "emerald-copper-deco"
   ],
   "rating": 4.7
  },
  {
   "id": "fatima-zahra",
   "name": "Fatima Zahra",
   "studio": "Maison Zahra",
   "country": "MA",
   "flag": "🇲🇦",
   "style": "Ornate Burgundy",
   "styleTags": [
    "burgundy",
    "ornate",
    "gold",
    "luxury",
    "black"
   ],
   "bio": "Fatima designs after-dark luxury — burgundy, jet black and ornate gold filigree for perfume and couture houses.",
   "avatar": "assets/artists/fatima-zahra.png",
   "since": 2021,
   "followers": 8784,
   "products": [
    "ivory-gold-ornate-book-box",
    "black-garment-bag",
    "black-perfume-box",
    "burgundy-rigid-lid-box",
    "black-perfume-drawer-box",
    "haute-abaya-black-shopping-bag"
   ],
   "collections": [
    "burgundy-gold-ornate",
    "black-burgundy-gold-luxury"
   ],
   "rating": 4.9
  },
  {
   "id": "elena-petrova",
   "name": "Elena Petrova",
   "studio": "Linea Nordica",
   "country": "FR",
   "flag": "🇫🇷",
   "style": "Charcoal Geometry",
   "styleTags": [
    "charcoal",
    "copper",
    "geometric",
    "diamond"
   ],
   "bio": "Elena draws crisp charcoal-and-copper grids — confident geometric systems for modern menswear and tech-lux brands.",
   "avatar": "assets/artists/elena-petrova.png",
   "since": 2016,
   "followers": 1588,
   "products": [
    "green-geometric-paper-gift-bag",
    "fine-jewels-green-ring-box",
    "jewelry-keepsake-box"
   ],
   "collections": [
    "charcoal-copper-diamond"
   ],
   "rating": 4.8
  },
  {
   "id": "rami-khoury",
   "name": "Rami Khoury",
   "studio": "Beirut Modern",
   "country": "LB",
   "flag": "🇱🇧",
   "style": "Teal Modern",
   "styleTags": [
    "teal",
    "gold",
    "geometric",
    "modern"
   ],
   "bio": "Rami balances teal and gold in clean modern geometry — contemporary luxury with a Levantine accent.",
   "avatar": "assets/artists/rami-khoury.png",
   "since": 2019,
   "followers": 1392,
   "products": [
    "personalized-magnetic-box",
    "cosmetic-tube",
    "custom-branded-garment-bag"
   ],
   "collections": [
    "teal-gold-geometric"
   ],
   "rating": 4.7
  },
  {
   "id": "isabella-santos",
   "name": "Isabella Santos",
   "studio": "Raposa Atelier",
   "country": "BR",
   "flag": "🇧🇷",
   "style": "Woodland Whimsy",
   "styleTags": [
    "woodland",
    "fox",
    "whimsy",
    "illustrated",
    "cream"
   ],
   "bio": "Isabella tells little forest stories — foxes, foliage and cream backdrops with a warm, collectible, storybook charm.",
   "avatar": "assets/artists/isabella-santos.png",
   "since": 2021,
   "followers": 3927,
   "products": [
    "cream-ribbon-magnetic-gift-box",
    "sugar-and-spice-bakery-box",
    "cafe-noir-coffee-cups"
   ],
   "collections": [
    "floral-fox-woodland"
   ],
   "rating": 4.7
  }
 ],
 "makers": [
  {
   "id": "imprint-atelier",
   "name": "Imprint Atelier",
   "country": "AE",
   "flag": "🇦🇪",
   "color": "#1a1a1a",
   "rating": 4.9,
   "leadDays": 7,
   "priceMul": 1.0,
   "moq": 250,
   "since": 2017,
   "reviews": 412,
   "capabilities": [
    "Offset + digital",
    "Foil & emboss",
    "Rigid box assembly",
    "Eco inks"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®",
    "ISO 9001",
    "G7 Master"
   ],
   "bio": "Imprint's flagship atelier in Dubai — the house standard for foil, emboss and rigid-box finishing, and the default for featured templates.",
   "products": [
    "honeyloom-gift-bag",
    "gold-mandala-paper-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "burgundy-chocolate-gift-box",
    "kraft-mailer-box-gold-emblem",
    "white-cake-box",
    "kraft-cylinder-tube",
    "blush-pink-round-gift-box",
    "ivory-jewelry-box-velvet",
    "black-garment-bag",
    "black-perfume-box",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "cream-ribbon-magnetic-gift-box",
    "black-patterned-mailer-box",
    "navy-velvet-ring-box",
    "white-window-gift-box-ribbon",
    "terracotta-cylinder-tube",
    "burgundy-rigid-lid-box",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "black-perfume-drawer-box",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "fine-jewels-green-ring-box",
    "curated-beauty-co-mailer-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "elara-cosmetics-perfume-set",
    "personalized-stationery-set",
    "luxury-paper-gift-bag",
    "personalized-magnetic-box",
    "custom-printed-cardboard-mailer-box",
    "cosmetic-tube",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "jewelry-keepsake-box",
    "custom-designed-folding-carton",
    "personalized-stationery-set-2",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "gulf-print",
   "name": "Gulf Print Works",
   "country": "AE",
   "flag": "🇦🇪",
   "color": "#0f6e63",
   "rating": 4.6,
   "leadDays": 9,
   "priceMul": 0.92,
   "moq": 500,
   "since": 2009,
   "reviews": 318,
   "capabilities": [
    "High-volume offset",
    "Litho-lam",
    "Window patching"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil"
   ],
   "certs": [
    "FSC®",
    "ISO 9001"
   ],
   "bio": "A Sharjah high-volume house — sharp pricing at scale for retail rollouts and seasonal campaigns.",
   "products": [
    "gold-mandala-paper-gift-bag",
    "burgundy-chocolate-gift-box",
    "kraft-mailer-box-gold-emblem",
    "white-cake-box",
    "kraft-cylinder-tube",
    "black-garment-bag",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "black-patterned-mailer-box",
    "terracotta-cylinder-tube",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "curated-beauty-co-mailer-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "personalized-stationery-set",
    "luxury-paper-gift-bag",
    "custom-printed-cardboard-mailer-box",
    "cosmetic-tube",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "personalized-stationery-set-2",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag"
   ]
  },
  {
   "id": "najm-packaging",
   "name": "Najm Packaging",
   "country": "SA",
   "flag": "🇸🇦",
   "color": "#1f7a5a",
   "rating": 4.7,
   "leadDays": 8,
   "priceMul": 1.04,
   "moq": 300,
   "since": 2014,
   "reviews": 276,
   "capabilities": [
    "Rigid & magnetic boxes",
    "Velvet lining",
    "Soft-touch lam"
   ],
   "finishes": [
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "ISO 9001",
    "ISO 14001"
   ],
   "bio": "Riyadh specialists in rigid and jewellery boxes — magnetic closures, velvet inserts and flawless wraps.",
   "products": [
    "honeyloom-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "blush-pink-round-gift-box",
    "ivory-jewelry-box-velvet",
    "black-perfume-box",
    "cream-ribbon-magnetic-gift-box",
    "navy-velvet-ring-box",
    "white-window-gift-box-ribbon",
    "burgundy-rigid-lid-box",
    "black-perfume-drawer-box",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "fine-jewels-green-ring-box",
    "elara-cosmetics-perfume-set",
    "personalized-magnetic-box",
    "jewelry-keepsake-box",
    "custom-designed-folding-carton",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "levant-press",
   "name": "Levant Press",
   "country": "LB",
   "flag": "🇱🇧",
   "color": "#b87333",
   "rating": 4.5,
   "leadDays": 12,
   "priceMul": 0.97,
   "moq": 200,
   "since": 2005,
   "reviews": 201,
   "capabilities": [
    "Artisan letterpress",
    "Hand assembly",
    "Specialty papers"
   ],
   "finishes": [
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®"
   ],
   "bio": "A Beirut craft press — letterpress, hand-assembly and specialty stock for small, beautiful runs.",
   "products": [
    "gold-mandala-paper-gift-bag",
    "navy-gold-floral-rigid-box",
    "ivory-gold-ornate-book-box",
    "burgundy-chocolate-gift-box",
    "white-cake-box",
    "blush-pink-round-gift-box",
    "black-garment-bag",
    "dark-chocolate-truffle-box",
    "green-geometric-paper-gift-bag",
    "cream-ribbon-magnetic-gift-box",
    "white-window-gift-box-ribbon",
    "burgundy-rigid-lid-box",
    "blush-pink-bouquet-wrap",
    "gray-garment-bag",
    "navy-tall-bottle-box",
    "ivory-cube-favor-boxes",
    "ab-monogram-navy-chocolate-box",
    "la-petite-boutique-pink-bags",
    "artisan-coffee-green-tin",
    "sugar-and-spice-bakery-box",
    "haute-abaya-black-shopping-bag",
    "bloom-and-petal-bouquet",
    "chocolate-atelier-truffle-box",
    "cafe-noir-coffee-cups",
    "luxury-paper-gift-bag",
    "personalized-magnetic-box",
    "bakery-box",
    "luxury-flower-bouquet-box",
    "custom-designed-folding-carton",
    "premium-rigid-chocolate-box",
    "custom-branded-garment-bag"
   ]
  },
  {
   "id": "crescent-press",
   "name": "Crescent Press",
   "country": "SA",
   "flag": "🇸🇦",
   "color": "#7a2738",
   "rating": 4.8,
   "leadDays": 10,
   "priceMul": 1.08,
   "moq": 150,
   "since": 2019,
   "reviews": 164,
   "capabilities": [
    "Luxury rigid",
    "UV spot",
    "Multi-level emboss",
    "Edge painting"
   ],
   "finishes": [
    "Gloss",
    "Matte",
    "Soft-touch",
    "Foil",
    "Emboss",
    "Deboss"
   ],
   "certs": [
    "FSC®",
    "ISO 9001",
    "Sedex"
   ],
   "bio": "Jeddah's luxury-only line — UV spot, sculpted multi-level emboss and painted edges for couture and fragrance.",
   "products": [
    "honeyloom-gift-bag",
    "ivory-jewelry-box-velvet",
    "black-perfume-box",
    "navy-velvet-ring-box",
    "black-perfume-drawer-box",
    "fine-jewels-green-ring-box",
    "elara-cosmetics-perfume-set",
    "jewelry-keepsake-box",
    "luxury-candle-gift-box"
   ]
  },
  {
   "id": "marina-pack",
   "name": "Marina Pack",
   "country": "QA",
   "flag": "🇶🇦",
   "color": "#2a3a5a",
   "rating": 4.4,
   "leadDays": 11,
   "priceMul": 0.95,
   "moq": 400,
   "since": 2012,
   "reviews": 148,
   "capabilities": [
    "Corrugated & mailers",
    "Flexo print",
    "Recycled board",
    "Mono-material"
   ],
   "finishes": [
    "Matte",
    "Kraft",
    "Foil"
   ],
   "certs": [
    "FSC®",
    "ISO 14001"
   ],
   "bio": "Doha's sustainability-forward mailer house — recycled, mono-material and plastic-free e-commerce packaging.",
   "products": [
    "kraft-mailer-box-gold-emblem",
    "black-patterned-mailer-box",
    "curated-beauty-co-mailer-box",
    "custom-printed-cardboard-mailer-box"
   ]
  }
 ],
 "collections": [
  {
   "id": "playful-abstract-multicolor",
   "name": "Playful Abstract Multicolor",
   "image": "assets/collections/playful-abstract-multicolor.png",
   "artist": "diego-reyes",
   "accent": "#e0556b",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "ivory-gold-lotus-luxury",
   "name": "Ivory Gold Lotus Luxury",
   "image": "assets/collections/ivory-gold-lotus-luxury.png",
   "artist": "layla-haddad",
   "accent": "#c79a63",
   "items": 6,
   "tags": []
  },
  {
   "id": "floral-fox-woodland",
   "name": "Floral Fox Woodland",
   "image": "assets/collections/floral-fox-woodland.png",
   "artist": "isabella-santos",
   "accent": "#cf7a92",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "teal-gold-geometric",
   "name": "Teal Gold Geometric",
   "image": "assets/collections/teal-gold-geometric.png",
   "artist": "rami-khoury",
   "accent": "#c79a63",
   "items": 12,
   "tags": []
  },
  {
   "id": "emerald-gold-deco-chocolate",
   "name": "Emerald Gold Deco Chocolate",
   "image": "assets/collections/emerald-gold-deco-chocolate.png",
   "artist": "hana-kim",
   "accent": "#c79a63",
   "items": 10,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "cream-kraft-minimal",
   "name": "Cream Kraft Minimal",
   "image": "assets/collections/cream-kraft-minimal.png",
   "artist": "liam-obrien",
   "accent": "#b9996a",
   "items": 6,
   "tags": []
  },
  {
   "id": "blush-kraft-natural",
   "name": "Blush Kraft Natural",
   "image": "assets/collections/blush-kraft-natural.png",
   "artist": "amara-okafor",
   "accent": "#b9996a",
   "items": 13,
   "tags": []
  },
  {
   "id": "emerald-copper-deco",
   "name": "Emerald Copper Deco",
   "image": "assets/collections/emerald-copper-deco.png",
   "artist": "hana-kim",
   "accent": "#1f7a5a",
   "items": 7,
   "tags": []
  },
  {
   "id": "neutral-taupe-botanical",
   "name": "Neutral Taupe Botanical",
   "image": "assets/collections/neutral-taupe-botanical.png",
   "artist": "liam-obrien",
   "accent": "#7a8a6a",
   "items": 11,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "white-gold-minimal",
   "name": "White Gold Minimal",
   "image": "assets/collections/white-gold-minimal.png",
   "artist": "yuki-tanaka",
   "accent": "#c79a63",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "woodland-botanical-cream",
   "name": "Woodland Botanical Cream",
   "image": "assets/collections/woodland-botanical-cream.png",
   "artist": "sofia-marchetti",
   "accent": "#8a6b4a",
   "items": 12,
   "tags": []
  },
  {
   "id": "charcoal-copper-geometric",
   "name": "Charcoal Copper Geometric",
   "image": "assets/collections/charcoal-copper-geometric.png",
   "artist": "omar-farouk",
   "accent": "#4a4a52",
   "items": 6,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "bold-abstract-colorful",
   "name": "Bold Abstract Colorful",
   "image": "assets/collections/bold-abstract-colorful.png",
   "artist": "diego-reyes",
   "accent": "#e0556b",
   "items": 10,
   "tags": []
  },
  {
   "id": "white-silver-minimal",
   "name": "White Silver Minimal",
   "image": "assets/collections/white-silver-minimal.png",
   "artist": "yuki-tanaka",
   "accent": "#9a958c",
   "items": 7,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "sage-wildflower-illustrated",
   "name": "Sage Wildflower Illustrated",
   "image": "assets/collections/sage-wildflower-illustrated.png",
   "artist": "sofia-marchetti",
   "accent": "#8a9a7a",
   "items": 10,
   "tags": []
  },
  {
   "id": "charcoal-copper-diamond",
   "name": "Charcoal Copper Diamond",
   "image": "assets/collections/charcoal-copper-diamond.png",
   "artist": "elena-petrova",
   "accent": "#4a4a52",
   "items": 8,
   "tags": []
  },
  {
   "id": "vibrant-multicolor-abstract",
   "name": "Vibrant Multicolor Abstract",
   "image": "assets/collections/vibrant-multicolor-abstract.png",
   "artist": "diego-reyes",
   "accent": "#e0556b",
   "items": 6,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "burgundy-gold-ornate",
   "name": "Burgundy Gold Ornate",
   "image": "assets/collections/burgundy-gold-ornate.png",
   "artist": "fatima-zahra",
   "accent": "#c79a63",
   "items": 15,
   "tags": []
  },
  {
   "id": "blush-pink-floral",
   "name": "Blush Pink Floral",
   "image": "assets/collections/blush-pink-floral.png",
   "artist": "amara-okafor",
   "accent": "#cf7a92",
   "items": 13,
   "tags": [
    "trending"
   ]
  },
  {
   "id": "navy-copper-moroccan",
   "name": "Navy Copper Moroccan",
   "image": "assets/collections/navy-copper-moroccan.png",
   "artist": "noor-al-rashid",
   "accent": "#b87333",
   "items": 14,
   "tags": []
  },
  {
   "id": "gray-kraft-mailer",
   "name": "Gray Kraft Mailer",
   "image": "assets/collections/gray-kraft-mailer.png",
   "artist": "liam-obrien",
   "accent": "#b9996a",
   "items": 10,
   "tags": []
  },
  {
   "id": "black-burgundy-gold-luxury",
   "name": "Black Burgundy Gold Luxury",
   "image": "assets/collections/black-burgundy-gold-luxury.png",
   "artist": "fatima-zahra",
   "accent": "#c79a63",
   "items": 7,
   "tags": []
  },
  {
   "id": "sage-blush-floral",
   "name": "Sage Blush Floral",
   "image": "assets/collections/sage-blush-floral.png",
   "artist": "amara-okafor",
   "accent": "#cf7a92",
   "items": 7,
   "tags": []
  },
  {
   "id": "navy-copper-moroccan-tin",
   "name": "Navy Copper Moroccan Tin",
   "image": "assets/collections/navy-copper-moroccan-tin.png",
   "artist": "noor-al-rashid",
   "accent": "#b87333",
   "items": 8,
   "tags": []
  },
  {
   "id": "kraft-gray-natural",
   "name": "Kraft Gray Natural",
   "image": "assets/collections/kraft-gray-natural.png",
   "artist": "liam-obrien",
   "accent": "#b9996a",
   "items": 12,
   "tags": []
  }
 ],
 "bags": [
  "assets/bags/bag-1.jpg",
  "assets/bags/bag-2.jpg",
  "assets/bags/bag-3.jpg",
  "assets/bags/bag-4.jpg",
  "assets/bags/bag-5.jpg",
  "assets/bags/bag-6.jpg",
  "assets/bags/bag-7.jpg",
  "assets/bags/bag-8.jpg",
  "assets/bags/bag-9.jpg",
  "assets/bags/bag-10.jpg",
  "assets/bags/bag-11.jpg",
  "assets/bags/bag-12.jpg",
  "assets/bags/bag-13.jpg"
 ]
};
